### ISSUE TITLE
Fix dashboard date display

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer#1009]
May be a mocks only issue but currently running `make start_test` displays submissions on the dashboard as Invalid date and iso string.

**Comment by Cooryd** [comment]
<img width="370" alt="Screenshot 2020-06-05 at 09 33 11" src="https://user-images.githubusercontent.com/22455561/83855422-f1205f00-a70f-11ea-9917-622254ba309a.png">

**Comment by hdrury1** [comment]
From #655 :

The submission object on the client application currently has the `updated` property set as a number type (typescipt type not graphql). The server is dealing with this value as an ISO string so the client should update its types, props types and unit test data to make it a string value.
