### ISSUE TITLE
Write eks update playbook

### ISSUE THREAD

**Issue by erkannt** [libero/reviewer#1025]
created due to #1020 

Kubernetes version upgrades are a manual process on aws eks.

Security updates are rolled out with the same process. Need to monitor https://alas.aws.amazon.com/alas2.html

Starting point/refs:

- https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html
- https://docs.aws.amazon.com/eks/latest/userguide/update-managed-node-group.html

---

ToDo:

- [x] write playbook
- [x] update eks to 1.15
- [x] check if playbook for draining nodes works
- [x] update playbook re: flux api access/restart of flux after upgrade

**Comment by erkannt** [comment]
Waiting for builder PR https://github.com/elifesciences/builder/pull/673

See notes on update: https://github.com/elifesciences/elife-flux-test/blob/master/docs/upgrading-eks.md

**Comment by erkannt** [comment]
Need to set up builder before I can move on.

**Comment by erkannt** [comment]
Completed playbook for our current worker node setup. Currently have to manually cordon, drain and kill nodes. Given the utilization of the cluster we'd probably first have to up the worker count via builder...

**Comment by erkannt** [comment]
Removing myself and placing this back into todo until above issue is fixed.

**Comment by Cooryd** [comment]
Update on this, (to the best of my memory from last weeks meeting) @giorgiosironi has been able to locally recreate the access issues @erkannt was having with accessing playbook so is now investigating why permissions are behaving differently.

**Comment by erkannt** [comment]
New 1.15 worker fails to reach ready state:

```runtime network not ready: NetworkReady=false reas
on:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninit
ialized
```

**Comment by erkannt** [comment]
Worker was failing to reach ready state due to the baseline PodSecurityPolicy being too restrictive for `aws-node` and `kube-proxy` daemonset. Creating a more permissive PSP bound to to `daemon-set-controller` for the `kube-system` namespace solves this.

**Comment by erkannt** [comment]
Playbook complete and validated. Created dedicated issue for the 1.16 upgrade #1176
