### ISSUE TITLE
Attach cluster to loggly

### ISSUE THREAD

**Issue by erkannt** [libero/reviewer#1028]
- Tooling? Loki looks good to me
- persistence?
- access/auth?

**Comment by erkannt** [comment]
@lsh-0 says we can go to production without this. But need to implement afterwards.

**Comment by lsh-0** [comment]
I did? what??

Logs go to Loggly, please.

**Comment by erkannt** [comment]
- Loggly docs have an [example with logspout](https://documentation.solarwinds.com/en/Success_Center/loggly/Content/admin/kubernetes-logging-through-logspout.htm), but this looks out of date
- a [blog post](https://www.loggly.com/blog/send-kubernetes-logs-loggly/) by them on using fluentd appears to be more current

**Comment by erkannt** [comment]
They also have a [guide](https://www.loggly.com/use-cases/guide-to-aggregating-and-monitoring-kubernetes-logs-with-loggly/) for using fluentd and kubernetes. The linked repo looks the most convincing so far.
https://github.com/christianhxc/kubernetes-logging-loggly/blob/master/manifests/loggly.yaml

**Comment by lsh-0** [comment]
The final result is that application logs end up in Loggly. Please use the right tool for the job and we can agonise over the details later. 

@NuclearRedeye might have some insight if you want to bounce ideas off of him, but ultimately the decision is yours.

**Comment by erkannt** [comment]
Set up loggly on flux-test cluster while I wait for help on deploying the production cluster. Will switch of loggly for test-cluster once prod is up.

Would you mind checking if the log ingestion looks okay @lsh-0? From what I see the easiest way to filter is by using the json kubernetes tree as that exposes all the labels we attach to the kubernetes objects.

**Comment by lsh-0** [comment]
Looking good:

![2020-08-04 11 21 56 elifesciences loggly com 6a7cafe9c465](https://user-images.githubusercontent.com/2142748/89244066-c0dc3a80-d644-11ea-9060-aeb7d9a4d809.png)
