### ISSUE TITLE
Journal doesn't check return url against whitelist

### ISSUE THREAD

**Issue by erkannt** [libero/reviewer#1041]
https://github.com/libero/reviewer/issues/837 was supposed to introduce:

pass desired return url as part of request (avoid hard coding in journal)
optionally get token back as part of url

The first feature was also supposed to check the return url against a whitelist and return a 400 if it wasn't on that list.

https://github.com/elifesciences/builder-configuration/pull/144/files added `*.elifesciences.org` to the whitelist.

Currently no matter what return url is passed in we alwas get a redirect, never a 400.

**Comment by nlisgo** [comment]
@thewilkybarkid I had a quick look and attempt to recreate the issue locally but without success. I think this could be a useful issue to pull you in for a moment to help me triage and then I can take it forward. I suggest that we jump on a call for 30 minutes some time next week and @erezmus could join too.

I will continue to investigate if I get a chance and update this ticket if I get anywhere.

**Comment by thewilkybarkid** [comment]
Is this in staging? How can I recreate it?

**Comment by erezmus** [comment]
so you either need to get @erkannt to change the nginx redirect or you can try adding the 'redirect_url' parameter as so:

https://continuumtest--cdn-journal.elifesciences.org/submit?return_url=https%3A%2F%2Flibero-reviewer--staging.elifesciences.org%2Flogin

**Comment by erkannt** [comment]
I can apply the change easily to https://libero-reviewer--staging.elifesciences.org/login if you need. But as this breaks our only staging deploy I have always reverted it afterwards.

**Comment by thewilkybarkid** [comment]
Bypassing the CDN (https://continuumtest--journal.elifesciences.org/submit?return_url=https%3A%2F%2Flibero-reviewer--staging.elifesciences.org%2Flogin) gives a 500, which looks to be https://elifesciences.loggly.com/search#terms=journal%20continuumtest&from=2020-06-16T09:15:25.243Z&until=2020-06-16T10:15:25.243Z&source_group=&event=a0cc6f38-afb9-11ea-8071-0683a0f56bee,1592302238000,138115950389784376

**Comment by thewilkybarkid** [comment]
Can't see anything obvious now.

**Comment by thewilkybarkid** [comment]
Doubt it will fix the problem, but moving https://github.com/elifesciences/journal/blob/f3ea6bb77a39523d0d6ac630d18f8aca47144753/src/Controller/SubmitController.php#L37-L58 above the is-the-user-authenticated check might expose something (since authenticating can't make an invalid `return_url` work).

**Comment by erezmus** [comment]
thanks @thewilkybarkid. Is there a way to get the stack trace on the error 500 ?

**Comment by thewilkybarkid** [comment]
Loggly entry is:

```json
{
  "message": "Uncaught PHP Exception Symfony\\Component\\DependencyInjection\\Exception\\InvalidArgumentException: \"The parameter \"submit_url_redirects\" must be defined.\" at /srv/journal/var/cache/continuumtest/ContainerDrcf1m8/journalContinuumtestProjectContainer.php line 1295",
  "context": {
    "exception": {
      "class": "Symfony\\Component\\DependencyInjection\\Exception\\InvalidArgumentException",
      "message": "The parameter \"submit_url_redirects\" must be defined.",
      "code": 0,
      "file": "/srv/journal/var/cache/continuumtest/ContainerDrcf1m8/journalContinuumtestProjectContainer.php:1295",
      "trace": [
        "/srv/journal/src/Controller/Controller.php:56",
        "/srv/journal/src/Controller/SubmitController.php:44",
        "/srv/journal/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151",
        "/srv/journal/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68",
        "/srv/journal/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200",
        "/srv/journal/src/AppKernel.php:114",
        "/srv/journal/web/app.php:39"
      ]
    }
  },
  "level": 500,
  "level_name": "CRITICAL",
  "channel": "request",
  "datetime": {
    "date": "2020-06-16 10:10:38.444533",
    "timezone_type": 3,
    "timezone": "UTC"
  },
  "extra": []
}
```

**Comment by thewilkybarkid** [comment]
https://github.com/elifesciences/journal-formula/blob/master/salt/journal/config/srv-journal-parameters.yml doesn't seem to include `submit_url_redirects`.

**Comment by erezmus** [comment]
Ah ok Im guessing we didn't configure that in the correct place in builder configuration repo. I'll take a look tomorrow.

Many thanks

**Comment by erezmus** [comment]
From discussion with @thewilkybarkid, following plan agreed:

1. Change journal code to move up the check for the new `request_url` and `token_in_query` query params to see if we can get the same behaviour with cdn and when bypassing
2. Update the journal formula so that the values from builder-configuration are passed in

**Comment by erezmus** [comment]
https://continuumtest--cdn-journal.elifesciences.org/submit?return_url=https%3A%2F%2Flibero-reviewer--staging.elifesciences.org%2Flogin

now gives a kaboom. shall we go ahead and do item 2? @thewilkybarkid

**Comment by thewilkybarkid** [comment]
👍 (Assume Loggly says it's the configuration issue.)

**Comment by erezmus** [comment]
looks like its working now with the cdn. can we close @thewilkybarkid
