### ISSUE TITLE
Clicking next is in wizard is some times unresponsive on first click

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer#1057]
- create new submission
- at author step click next to show validation errors from empty fields
- fill details and immediately click next

can also reproduce by deleting one filled in input, clicking next to run validation, adding text to resolve validation and immediately clicking next.

Second click seems to work fine. Leaving the form for a moment before clicking also seems to work so could this be a async validation issue?

**Comment by erkannt** [comment]
I think this might be the cause of this saucelabs failure:

https://app.eu-central-1.saucelabs.com/tests/db3ef648e09a4b0fa21dc5ed98beb15f#1

```
 ✖ Happy path

   1) AssertionError: expected false to be truthy

      Browser: Firefox 77.0 / Windows 10

   (https://app.eu-central-1.saucelabs.com/tests/db3ef648e09a4b0fa21dc5ed98beb15f)

         39 |        }
         40 |        throw new Error(`${status} this value is an unknown
      file status!`);
         41 |    }
         42 |
         43 |    public async assertOnPage(): Promise<void> {
       > 44 |        await t.expect(this.stepWrapper.visible).ok();
         45 |    }
         46 |
         47 |    public async fillCoverLetterInput(
         48 |        value = 'Lorem ipsum dolor sit amet, consectetur
      adipiscing elit.',
         49 |    ): Promise<void> {

         at FilesPage.<anonymous>
```

**Comment by erkannt** [comment]
Had another failure: https://github.com/libero/reviewer-client/runs/773452600?check_suite_focus=true
