### ISSUE TITLE
browsertests fail in umbrella repo but not in client

### ISSUE THREAD

**Issue by erkannt** [libero/reviewer#1062]
Has been failing since last week: https://github.com/libero/reviewer/actions/runs/126015261

Probably a diff between mocks and submission.

```
 Running tests in:
 - Chrome 83.0.4103.97 / Linux 0.0

 Getting Started
 ✓ assert nav bar
 ✓ My first test
 ✖ Happy path

   1) AssertionError: expected false to be truthy

      Browser: Chrome 83.0.4103.97 / Linux 0.0

         52 |        await t.expect(Selector('#peoplePickerSearch').visible).ok();
         53 |        const addButtonSelector =
      Selector('.people-picker__modal_list--item .pod__button');
         54 |
         55 |        for (let i=0; i < number; i++) {
         56 |            const button = addButtonSelector.nth(i);
       > 57 |            await t.expect(button.visible).ok();
         58 |            await t.click(button);
         59 |        }
         60 |
         61 |        await

   t.expect(Selector('.people-picker__selected-tabs').child('.people-picker__selected-tab').count).eql(number);
         62 |        await
      t.click(Selector('.modal__buttons_container').find('.button--primary'));

         at EditorPage.<anonymous>
      (/home/hff/code/libero/reviewer-client/tests/page-objects/EditorPage.ts:57:44)
         at fulfilled
      (/home/hff/code/libero/reviewer-client/tests/page-objects/EditorPage.ts:5:58)



 1/3 failed (37s)
```

To reproduce locally I have added `start_master_localhost` to the umbrella repo make targets:

- checkout `reviewer` master
- update client image in `docker-compose.master.yml` to `master-89a2034d-20200612.1028`
- `make start_master_localhost`
- checkout `reviewer-client` `89a2034d` i.e. current master
- `make test_browser` for headless or `yarn test:browser`

**Comment by diversemix** [comment]
I've managed to reproduce this locally on current master:
- client `b1533cca0f01389662f9a01590b0c831dbe661d8`
- reviewer  `58e4574b2c8fd64f9dc66247eb409248ffd9e9a0`

**Comment by diversemix** [comment]
ok - this is funny - the reason it fails is because there is no one to pick ... mock only has two Senior Editors you can choose - the these were selected to include - therefore there is nothing to show when excluding :laughing:  ... let me add some more.

**Comment by diversemix** [comment]
Looks like reviewer-mocks is building the container with the wrong mock-data in ... Cannot for the life of me find where its coming from - when I build locally its all good :disappointed:

**Comment by diversemix** [comment]
ok my bad - locally in mocks I added the complete set for testing - so after lunch will add more redacted senior editors :)
