### ISSUE TITLE
#BlackLivesMatter Rename all master branches to main

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#1065]
Repos:
- [ ] continuum-adapter
- [ ] reviewer-mocks
- [ ] reviewer-submission
- [ ] reviewer-docs
- [ ] reviewer-client
- [x] reviewer-reporter
- [ ] reviewer 

What will this affect?
- [ ] Infrastructure
- [ ] docker deployments?

**Comment by diversemix** [comment]
Seems people are doing this with two simple commands:
```
git branch -m master main
git push -u origin main
```

**Comment by diversemix** [comment]
Update local clones with:
```
git checkout master
git branch -m master main
git fetch
git branch --unset-upstream
git branch -u origin/main
git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main
```

**Comment by diversemix** [comment]
Working on a script https://gist.github.com/diversemix/eea486a9d680d64b319e924cb4bd4572

**Comment by diversemix** [comment]
Marked this as blocked until we have a discussion as to the best time to co-ordinate on this.

**Comment by diversemix** [comment]
Now this has been sorted on a single repo - putting it back into Todo as we are not at a suitable stage to carry out the rest of the work.

**Comment by NuclearRedeye** [comment]
GitHub have an [issue on their roadmap](https://github.com/github/roadmap/issues/63) to do some work on this behind the scenes. I think it would be wise to monitor what they do and how that works before making any immediate changes our end.
