### ISSUE TITLE
Amend article types offered by the wizard

### ISSUE THREAD

**Issue by hdrury1** [libero/reviewer#1072]
The wizard should have the following option in the article type dropdown menu:

- Research Article
- Short Report
- Tools and Resources
- Feature Article
- Scientific Correspondence
- Research Advance
- Review Article

If a user selects 'Review Article' or 'Research Advance' they should NOT be allowed to proceed through the wizard. Clicking 'Continue' should redirect to eJP.

**Comment by hdrury1** [comment]
To be tackled as part of review with @chugginselifesciences

**Comment by chugginselifesciences** [comment]
I'm happy for this to be done before we review together if it helps keep the focus on the visuals/interactions for the dropdown menu.
