### ISSUE TITLE
Scrollbar not linked to content on editor selection page

### ISSUE THREAD

**Issue by erkannt** [libero/reviewer#1100]
Scrolling through editors when adding them doesn't move scrollbar but no other content visible that is logically linked to scrollbar.

**Comment by norisalsaadie** [comment]
Cannot reproduce. It is believed this was addressed a couple of weeks ago via the following:

`useEffect(() => {
        if (isShowing) {
            document.body.setAttribute('style', 'overflow: hidden;');
        } else {
            document.body.setAttribute('style', '');
        }
    }, [isShowing]);`
