### ISSUE TITLE
Review Article Types being used

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer#1115]
These can be found in the select when starting a new submission. The list should be as follows:
- Research Article
- Short Report
- Tools & Resources
- Scientific Correspondence
-Feature Article

Remember to check xpub for the keys being used as they will need to remain consistent.

**Comment by hdrury1** [comment]
This ticket encompasses work to match what is currently in production in xPub, i.e. the option to submit:

- Research Article
- Short Report
- Tools and Resources
- Scientific Correspondence
- Feature Article

Each selection should result in different accompanying information text in accordance with this file:

https://docs.google.com/document/d/1noVVteQN8CgWZg2QLDW9Jgn0E3rhlS-QCFLQkj7YYP0/edit

Note that we should remove the Research Advance option from the dropdown for now. There is potential future work to re-introduce it and link out to eJP to enable a user to complete a Research Advance submission.

See https://elifesciences.slack.com/archives/C6MJK1RD4/p1592217544014700 for further context.
