### ISSUE TITLE
Fix bug with manuscriptDetails and disclosure form values not being saved

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer#1120]
In staging neither the `manuscriptDetails` fields or `disclosure` fields are being persisted by the server. Investigate why and fix.

**Comment by norisalsaadie** [comment]
The values are persisted in xpub-submission-repo and the entryToModel does include manuscriptDetails fields and disclosure. Which step was this noticed on?

**Comment by norisalsaadie** [comment]
This integration test here suggested that it is persisted https://github.com/libero/reviewer-submission/blob/master/tests/wizard.pages.test.ts#L61-L101
