### ISSUE TITLE
wait for browsersession to become available on saucelabs/browserstack - take 2

### ISSUE THREAD

**Issue by norisalsaadie** [libero/reviewer#1131]
Picks from https://github.com/libero/reviewer/issues/1002

One possible solution is to use a turnstyle CI task https://github.com/softprops/turnstyle found via https://github.community/t/how-to-limit-concurrent-workflow-runs/16844

Update:

Turnstyle was attempted but is not feasible.

Example PR https://github.com/libero/reviewer-client/pull/311

Update:

Tried modifying the CI job to stop using a matrix to run the tasks, instead, it would attempt to run them via the cli e.g. `yarn testcafe saucelabs:Safari,saucelabs:Chrome,saucelabs:Firefox,saucelabs:MicrosoftEdge tests/**/*.browser.ts`

Example result: https://github.com/libero/reviewer-client/pull/317/checks?check_run_id=811496974

Update: there were attempts to limit the concurrency via the flag `-c integer` but that failed. 

Update: 

Doesn't solve the issue. Tried the runner locally using an array e.g: 
```
await runner
        .browsers(['chrome', 'firefox'])	        
        .src('./tests/browser-tests/Example.browser.ts')
        .src('./**/*.ts')
        .run();
```

Update:

The plugin used to run sauce labs https://github.com/DevExpress/testcafe-browser-provider-saucelabs does have retry logic baked in:

The parameters are outlined here:

https://github.com/DevExpress/testcafe-browser-provider-saucelabs/blob/master/src/index.js#L13-L16

The connector logic retries here https://github.com/DevExpress/testcafe-browser-provider-saucelabs/blob/master/src/index.js#L181-L207

This in turn uses the sauce labs connector outlined here https://github.com/DevExpress/saucelabs-connector/blob/master/src/index.js this manages the tunnel

**Comment by norisalsaadie** [comment]
Update:

Turnstyle was attempted but is not feasible.

Example PR libero/reviewer-client#311

Update:

Tried modifying the CI job to stop using a matrix to run the tasks, instead, it would attempt to run them via the cli e.g. yarn testcafe saucelabs:Safari,saucelabs:Chrome,saucelabs:Firefox,saucelabs:MicrosoftEdge tests/**/*.browser.ts

Example result: https://github.com/libero/reviewer-client/pull/317/checks?check_run_id=811496974

Update: there were attempts to limit the concurrency via the flag -c integer but that failed.

Update:

Doesn't solve the issue. Tried the runner locally using an array e.g:

await runner
        .browsers(['chrome', 'firefox'])	        
        .src('./tests/browser-tests/Example.browser.ts')
        .src('./**/*.ts')
        .run();

**Comment by norisalsaadie** [comment]
Update:

The plugin used to run sauce labs https://github.com/DevExpress/testcafe-browser-provider-saucelabs does have retry logic baked in:

The parameters are outlined here:

https://github.com/DevExpress/testcafe-browser-provider-saucelabs/blob/master/src/index.js#L13-L16

The connector logic retries here https://github.com/DevExpress/testcafe-browser-provider-saucelabs/blob/master/src/index.js#L181-L207

This in turn uses the sauce labs connector outlined here https://github.com/DevExpress/saucelabs-connector/blob/master/src/index.js this manages the tunnel

**Comment by erkannt** [comment]
If getting testcafe to wait is taking too long we could switch to a different branching/testing strategy where we only run against a single saucelabs browser (or none at all) on PR and only run against all browsers before merging to master.

**Comment by Cooryd** [comment]
On looking into this we've decided the only options for fixing this are:
- paying for more connections (this is probably an over simplification)
- coming up with some complex queuing service between CI tasks (this would be a hugely unjustifiable about of work)

To minimise the impact of this issue we are going to go for the third option of:
- disable saucelabs jobs on PRs and only run on merge to master.

**Comment by erkannt** [comment]
Closing. New issue: #1213
