### ISSUE TITLE
Styling: Editors page and people picker

### ISSUE THREAD

**Issue by chugginselifesciences** [libero/reviewer#1142]
- [x] Person pod selected state - the tick looks bigger than in xPub - would be good to match
- [x] Add/cancel in People Picker - please use the grid/align with the person pods
- [x] People Picker search box looks too tall, or the icon looks off centre
- [x] Please add the same xPub people picker search placeholder text
- [x] Can we prevent scrolling behind the modal? 
- [ ] Suggesting or excluding reviewers - avoid validation errors until adding another reviewer or pressing "next"
(currently it shows an error on email address as soon as the name is being entered)
- [x] The link about reviewer diversity should link to the relevant section of the Author Guide

I'd also like to check the People Picker in staging if possible before launch, but can raise any issues in another ticket.
We also talked about increasing the space for the research interests text in the person pod but can address that later.

**Comment by norisalsaadie** [comment]
> Suggesting or excluding reviewers - avoid validation errors until adding another reviewer or pressing "next"
> (currently it shows an error on email address as soon as the name is being entered) 

will be moved to it's own ticket
