### ISSUE TITLE
Submitted status not reflected/respected

### ISSUE THREAD

**Issue by erkannt** [libero/reviewer#1162]
Multiple issues:

- wizard is still a form after submission (shouldn't it be read only?)
- autosave still happening after submitted
- submit button can still be clicked
- dashboard lists submission as 'Continue Submission'
- Delete icon still visible (can be clicked but backend throws error)

After discussion with @hdrury1 we need to implement the following:

- [x] remove trashcan and delete action
- [x] submission isn't clickable after submitted
- [x] Status displayed: "Submitted: Check e-mail"

See also https://github.com/elifesciences/elife-xpub/issues/2402 and associated PR in xpub: https://github.com/elifesciences/elife-xpub/pull/2404

**Comment by norisalsaadie** [comment]
Closed as per part of a few PRs between submission and client.
