### ISSUE TITLE
Investigate: Look at lighthouse performance report and raise issues to increase performance

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer#1212]
https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Flibero-reviewer--staging.elifesciences.org%2F

To help improve browser test speed / reliability and general usage of the app we should look at the lighthouse report and identify the biggest bottlenecks then raise issues to address.

**Comment by norisalsaadie** [comment]
Immediate Issues:

- Too many chunks in the overall bundle - 117 HTTP requests to build the page (104 are scripts)
- Too much work on the main thread where JS eval can take ~1.5 seconds
