### ISSUE TITLE
Use HTTP2

### ISSUE THREAD

**Issue by norisalsaadie** [libero/reviewer#1217]
Browser support is there and it makes sense for complex bundles (lots of small chunks) on the client side https://caniuse.com/#feat=http2

Tasks:

- [x] add SSL cert/key to cluster as Secret
- [x] research aws ELB/nginx-ingress settings
- [x] update nginx-ingress on test-cluster
- [x] check if https force redirect works
- [x] apply to production cluster

**Comment by erkannt** [comment]
This will require changes to the SSL termination for the cluster as HTTP/2 requires SSL. Currently this is handled by the ELB. We will have either provide the ingress with access to the cert so that it handles the termination or configure it with a different cert and nest the SSL.

**Comment by erkannt** [comment]
A [default SSL cert](https://kubernetes.github.io/ingress-nginx/user-guide/tls/#default-ssl-certificate) can be set for ingress-nginx in the helm chart values `extraArgs`.

**Comment by erkannt** [comment]
Waiting for prod cluster so that I can test this without breaking things.

**Comment by erkannt** [comment]
Relevant docs re: aws annotations for nginx-ingress: https://kubernetes.github.io/ingress-nginx/deploy/#aws

**Comment by erkannt** [comment]
the existing classic node balancer wasn't automatically destroyed by the switch to NLB in the ingress-nginx annotations. Had to manually delete it.
