### ISSUE TITLE
Are we auditing in the right places? (check xpub for parity)

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer#1222]

**Comment by norisalsaadie** [comment]
Some findings based on xpub searches:

- warning logs - https://github.com/elifesciences/elife-xpub/search?q=logger.warn%28&unscoped_q=logger.warn%28 (9 returns) - reviewer has similar logs or better
- info logs - https://github.com/elifesciences/elife-xpub/search?q=logger.info%28&unscoped_q=logger.info%28 (14 returns) -  reviewer has similar logs or better
- error logs - https://github.com/elifesciences/elife-xpub/search?q=logger.error&unscoped_q=logger.error (21 returns) -  reviewer has similar logs or better
- all logs - https://github.com/elifesciences/elife-xpub/search?q=logger.&unscoped_q=logger. (54 returns) -  reviewer has similar logs or better


Updates to follow on branch 1222-logs
