### ISSUE TITLE
File Upload: Indeterminate Spinner before and after file upload

### ISSUE THREAD

**Issue by chugginselifesciences** [libero/reviewer#1241]
Hi. After testing a few typical files on staging I find file upload to show an indeterminate spinner at 0% for a very long time before only a second at most where the progress from 0% to 100% is shown. At 100% there is another indeterminate spinner for a few seconds which shows 100% file upload.

The intention was only to show an indeterminate spinner at the end during sciencebeam extraction as a 'fix' for file upload appearing to hang at 99% or 100% on xPub. This indeterminate progress spinner at the end of the process was meant to show "Processing" instead of staying on 100% file upload. I do not believe it was intended for an indeterminate spinner to be shown before file upload.

I have tried to breakdown the problem below and would appreciate help in understanding what we can do to resolve this:

- Before switchover we should at least change the `Upload manuscript 100%` label to `Processing` shown below the 2nd indeterminate spinner. I would be happy to raise another ticket if needed. The design is at the bottom of this ticket.

- I'd like to understand if the first indeterminate spinner is necessary, or a bug. If it is not intended I would like to see if we can start with the determinate progress going from 0% to 100% without any apparent delay at 0% or 100%. Please advise if I need to raise a ticket for an investigation.

- If we must have some sort of indeterminate progress shown at first, I think it is only helping if it is much quicker than it is currently. The actual file upload progress is very fast, so is almost pointless. I have only tried with files ~5Mb so far though.

- If we cannot resolve either the very long indeterminate spinner at the start, or the very fast file upload progress perhaps we should at least look at changing the labels to be more useful.

I've so far tested on Chrome on Firefox on desktop only.
Thanks

**Some screenshots for reference:**

First indeterminate spinner:

![image](https://user-images.githubusercontent.com/41907215/88934279-5b6d0000-d278-11ea-9e73-e7288d83467d.png)

Second indeterminate spinner:

![image](https://user-images.githubusercontent.com/41907215/88934245-4b552080-d278-11ea-8b50-9139f769c41c.png)

Design for the "sciencebeam extraction" step:
![image](https://user-images.githubusercontent.com/41907215/88936133-76d90a80-d27a-11ea-9725-58653182ed6d.png)

**Comment by hdrury1** [comment]
For File Upload:

Remove percentage from first stage with indeterminate spinner

**Comment by chugginselifesciences** [comment]
Instead of `Upload Manuscript 0%`

During spinner:
`Uploading manuscript`
During upload:
`Uploading manuscript x%`
During second spinner:
`Processing`
