### ISSUE TITLE
staging flow from continuumtest blue button click is broken (try hitting https://continuumtest--cdn-journal.elifesciences.org/submit)

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer#1276]
To reproduce:

- go to https://continuumtest--cdn-journal.elifesciences.org
- If you're logged it (theres a black and white profile menu in the top right corner) then the blue 'submit my research' button will go to 'https://continuumtest--cdn-journal.elifesciences.org/submit', click this and you'll be forwarded to 'https://libero-reviewer--staging.elifesciences.org/auth-redirect#{token}'. This should be using the query param 

- If you're not signed in when visiting https://continuumtest--cdn-journal.elifesciences.org you'll see a green button instead of the profile in the top right. The blue 'submit my research' button goes to 'https://libero-reviewer--staging.elifesciences.org/auth-redirect' this is incorrect, you should be going to 'https://libero-reviewer--staging.elifesciences.org/login'

**Comment by Cooryd** [comment]
Looking into journal code 'https://continuumtest--cdn-journal.elifesciences.org/submit' will return to 'https://libero-reviewer--staging.elifesciences.org/auth-redirect#{token}' correctlybecause it's missing the query params to return using a token query param (`&token_in_query=true`) not sure if using that requires a `return_url` as well or if you can get away with 'https://continuumtest--cdn-journal.elifesciences.org/submit?token_in_query=true' on its own

**Comment by erkannt** [comment]
After investigating with @norisalsaadie 

Required changes:

add `token_in_query` to `submit_url` variable in https://github.com/elifesciences/builder-configuration/blob/master/pillar/environment-continuumtest-public.sls

Getting the `token_in_query` to work would require us to change the url generation for the button. Preferably with a flag to enable/disable xpub/reviewer compatibility.
We could instead:

- accept that in the beginning users will be asked to login again even if logged into the journal
- once we no longer want to be able to go back to xpub, remove the legacy token behavior in the journal code (https://github.com/elifesciences/journal/blob/ad71c54e58bbf92f033957c8677fe44c105030bc/src/Controller/SubmitController.php#L60)

Opions? @Cooryd

**Comment by erkannt** [comment]
Doesn't appear to be deployed yet. Asking what we need to run...

**Comment by erkannt** [comment]
Looks like its redirecting to `/login` now, so I'm closing this.
