### ISSUE TITLE
Supporting files: queued and downloading states

### ISSUE THREAD

**Issue by chugginselifesciences** [libero/reviewer#1280]
Supporting files appear to be queued for a long time before download (similar to manuscript file upload) and are showing an indeterminate spinner instead of simply a grey circle. Seems related to #1241 

Files appear to be in a queued state for a while before uploading, even if uploaded one at a time.

Screenshot:
![image](https://user-images.githubusercontent.com/41907215/89786350-b245c580-db13-11ea-8b6d-7e82b14753ea.png)

Intended states:

![image](https://user-images.githubusercontent.com/41907215/89786437-d4d7de80-db13-11ea-926c-c549a7825161.png)

**Comment by norisalsaadie** [comment]
Closed by https://github.com/libero/reviewer-client/pull/377
