### ISSUE TITLE
Investigate the use of Libero Pattern Library styles within reviewer

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer#131]
As we are now using SASS styling, we should try to make use of any existing styling found in the Libero Pattern Library that might fit with the reviewer UI designs.

**Comment by Cooryd** [comment]
We've found that out of the box the styles in pattern library don't fit well with the sizing / spacing of reviewer but there are similarities in some of the core components. From talking to @chugginselifesciences it's intended that the Publisher has its own specific styling which targets displaying content and we should not aim to align Reviewer's styling with Publisher. 

It will be more likely that component styling will be shared between the 'authenticated' applications such as Reviewer, Dashboard and Producer so there is reason for us to continue developing these component styles in a modular re-usable way.

Coming away from this investigations there are a few action points we should address to maximise reusability in our styling code.

**Properly identify shared components**

We should go through the Publisher and Reviewer components and group them in the following way:

- Identical Patterns / Components that are intended to be exactly the same across ALL products. This is styling that is completely consistent across the products without the need for any changes to configuration. These could be compiled into a common styleguide package and would include things like colour variables, atomic components such as buttons and link styling ect. We should confirm with Chris and Nick that these are intended to be the same through out the products and that a change to the general styling of one would likely mean a change to all (ie: font types).

- Similar Patterns / Components that may share underlying styling code but would need to be configured differently between the different applications. This might be something like the grid system which would need to use different width and spacing between products but might make use of the same core styling. This may be worth putting in the 'shared' styleguide package if it can be agreed that the components are supposed to have similar albeit differently configured style rather that it just being a coincidence between the two products. 

- Completely bespoke styling. We should consider if this styling is only bespoke to the 'authenticated` product suite or to the individual product. ie: might the progress bar be used within any of the other Libero apps or is it only for use in Reviewer? This one will be harder to identify right now as we aren't sure what some of the other products will look like, however we should ask the designers so that we can plan to give these components generic class names and make them extendable.

**Consider how we might package a shared set of styles** 
Libero Pattern Library doesn't export its styling as a stand alone package and makes use of symlinks to its vendor files which isn't ideal for porting it across to other projects. Ideally (for our use-case at least) we would like to package the styling up into an npm package making use of npm dependencies and standard sass vendor import syntax (`@import '~packageName';`). 

If we could identify the common styleguide components and compile all of their styling into an importable npm package both Pattern Library and Libero Reviewer could pull this package down and make use of it. I believe this would make more sense then trying to compile the whole pattern library into a package for now as there is a lot in there that is very specific to Publisher and won't be relevant to any of the other Libeero products.

/cc @diversemix @will-byrne @davidcmoulton @thewilkybarkid

**Comment by thewilkybarkid** [comment]
> Libero Pattern Library doesn't export its styling as a stand alone package and makes use of symlinks to its vendor files which isn't ideal for porting it across to other projects.

That's not true, `build/export` _is_ a standalone package.

> Ideally (for our use-case at least) we would like to package the styling up into an npm package making use of npm dependencies and standard sass vendor import syntax (`@import '~packageName';`).

Took a while to work out you actually meant webpack rather than anything to do with Sass (https://www.npmjs.com/package/sass-loader#imports).

We talked a bit about where the export would go, but kept it agnostic at least for the moment (since the 1 current use case isn't using npm).

> If we could identify the common styleguide components and compile all of their styling into an importable npm package both Pattern Library and Libero Reviewer could pull this package down and make use of it. I believe this would make more sense then trying to compile the whole pattern library into a package for now as there is a lot in there that is very specific to Publisher and won't be relevant to any of the other Libeero products.

The Pattern Library is the source, not a consumer.
