### ISSUE TITLE
Create http endpoint for preStop hook

### ISSUE THREAD

**Issue by erkannt** [libero/reviewer#1310]
We want to keep file uploads alive during rollouts of submission for a certain grace period.

This will partially rely on the k8s feature of `preStop` hooks. These delay the sending of SIGTERM until the hook(s) have completed. The hooks can be commands executed inside the container or http requests.

Note that if the overall grace period is exceeded during the preStop hook the container will receive a SIGKILL.

To avoid waiting needlessly, say by using `sleep`, we ideally need an http endpoint that answers with 200 once all or at least the upload connections have been closed.

This is a requirement for #998 and a precursor to the validation on submission in #1306

**Comment by norisalsaadie** [comment]
After careful consideration, it made more sense to gracefully handle sigterm and wait for the close event to be handled.  As reflected in https://github.com/libero/reviewer-submission/pull/223
