### ISSUE TITLE
Team photos in contact pages are very slow to load

### ISSUE THREAD

**Issue by chugginselifesciences** [libero/reviewer#1336]
![image](https://user-images.githubusercontent.com/41907215/91033508-6149cd00-e5fb-11ea-8939-c44b7f678e71.png)

This covers both the Editorial and Production team pages.

**Comment by Cooryd** [comment]
These images should be through iiif so we should be able to get lower res using the url (see https://iiif.elifesciences.org/journal-cms/person%2F2019-03%2Fmike.jpg/0,0,7600,4164/251,142/0/default.jpg as an example)
