### ISSUE TITLE
Autosave timing issue with submit

### ISSUE THREAD

**Issue by erkannt** [libero/reviewer#1387]
## What happened?

Browsertests fail when run against staging. 

save of submission state gets called after 'Confirm' has changed the state of the submission. Leading to an error 'User not permitted...'

## Can it be recreated?

- export all the ORCID envvars
- `npx testcafe chrome --fixture-meta fixtureID=staging`

**Comment by norisalsaadie** [comment]
Closed as part of https://github.com/libero/reviewer-client/pull/412
