### ISSUE TITLE
Error ribbon persisting on dashboard and static pages

### ISSUE THREAD

**Issue by chugginselifesciences** [libero/reviewer#1424]
## What happened?
The error ribbon persists on the dashboard and static pages.

The ribbon shown when attempting to progress in the wizard while there are errors/input required should be hidden if the user goes to the dashboard or static pages.

## Can it be recreated?
Open a new submission and attempt to continue to another step without fixing errors (to show the ribbon). Then press a link in the navigation bar. You should see the ribbon remain, when it should not be there.

### Screenshot
![image](https://user-images.githubusercontent.com/41907215/93477400-dfe01480-f8f2-11ea-811f-92507e2364eb.png)

## What did you expect to happen?
The ribbon should be hidden when leaving the submission. It does not need to persist/reappear when the user returns to the submission unless/until they attempt to continue without fixing errors.

**Comment by norisalsaadie** [comment]
Closed by https://github.com/libero/reviewer-client/pull/432
