### ISSUE TITLE
Entry on 'Details' page persists even after removal

### ISSUE THREAD

**Issue by erkannt** [libero/reviewer#1427]
## What happened?

Entered data on Details page, changed my mind, removed it, returned to page and it still has my original entry.

## Can it be recreated?

2. create submission
3. go to details
4. select any of the checkboxes
5. enter some text
6. click next
7. click previous
8. remove text and/or deselect box
9. click next
10. click previous

Text is back and so is the selection...

## What did you expect to happen?

My changes to be saved when I click next.

**Comment by hdrury1** [comment]
Reopening this one, as it wasn't addressed by the previous PR

From Slack:

> Hi @here, not sure if this https://elifesciences.slack.com/archives/C025LBBR4/p1600345574060800 should now be resolved or if you are still working on it but I have gone to test a Tools and Resources article and with the 'This manuscript has previously been considered by eLife' option in the details tab - this is reselected if it is unselected and then you move to the next tab and go back to details (I went back and forward a few times and it seemed less persistent with the other two tick boxes)
