### ISSUE TITLE
Add client side configuration

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer#164]
We need to add client side configuration which can change depending on the environment being used to run the application. Consider the following:

- It should be simple to identify which configuration options are being used when running the application in different contexts (CI vs development vs prod). And it should be easy to set which context you would like to run the application in (example: theres a bug only occurring in CI we should easily be able to replicate configuration locally).
- Unit tests should be able to easily set their own configuration at the individual test case level if needed. We previously had a set of `unit-test` configuration files which wasn't ideal and made testing difficult. How might we prevent this? Dependency injection? react context stored config? 
- Should we configure application environment configuration separately to application functionality configuration (API location vs logo customisation)? if so should they use the same format? (.env vs config package)?

This will likely require some discussion and agreement across the team (maybe wider tech team?) This issue should be used to begin this process by offering some options. The aim of this issue should be to unblock any other issues which are awaiting a config solution even if the given solution is subject to change.

**Comment by Cooryd** [comment]
Didn't notice we're already using `webpack.DefinePlugin` to server up an `API_HOST` configuration variable based on the values in the `.env` file. This is enough to unblock some things but we should figure out if we want to be putting things like feature flags and app configuration into that `.env` file and map with webpack plugins too or somewhere else. We should also document how to add new config options as well.

**Comment by erezmus** [comment]
I think there are two options:
* use environment variables configuration to expose global variables like API_HOST
* use a configuration tool that provides sane defaults which can be overridden via environment variables. https://github.com/mozilla/node-convict might be worth a look
