### ISSUE TITLE
Some auth service

### ISSUE THREAD

**Issue by petereast** [libero/reviewer#170]
I've started bashing out a spec for it: https://docs.google.com/document/d/19gIqGho9Od4hdPb9-zbmGUilz5UV3rOCNNKJsaE-5PA/edit#heading=h.x69n6i4266c6 we need to get this done before we can integrate libero reviewer with elife

**Comment by diversemix** [comment]
@petereast ... is this now done? Do we want to reference the types / interfaces here?
