### ISSUE TITLE
We need some way to lookup map between orcid/email/people/profile

### ISSUE THREAD

**Issue by petereast** [libero/reviewer#198]

**Comment by erezmus** [comment]
- Email addresses seem to be in in profiles.
- Orcids are in profiles and people (if present)
- Doesn't seem to be a way to search by orcid

**Comment by diversemix** [comment]
I think we should populate the token with the ORCiD and the email - after querying the journal/ profiles. Putting this into `continuum-auth` means that its specific to that component (which it is). But it also mean any other auth component developed will need to perform a similar function - which I think is fair enough. 

So if we wrote a `google-auth` component then that may well have in the email but no ORCiD.

/fyi @hdrury1

**Comment by erezmus** [comment]
Gonna add a PR to update continuum-auth so that email is added as part of meta in the UserIdentity type

**Comment by diversemix** [comment]
@erezmus ... or is it extending `UserIdentity` with a `ContinuumIdentity` (email+ORCiD)?
