### ISSUE TITLE
Find a way to toggle accessibility extension with config

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer#200]
Currently we include the `Tota11y` accessibility checker in all builds of the app. This should only be included in some builds (either `development` or builds with a new .env config option enabled).

**Comment by Cooryd** [comment]
This doesn't seem to be too straight forward as to wrap the import in an `if` check in the app would require the use of  [dynamic imports](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html) which would require us to change the `tsconfig.json` to output to `esnext` this would mean we couldn't guarantee IE support. Possible solutions are to have a seperate build script (`yarn build:es6` that points to an specific `esnext` configured `tsconfig` OR we might want TS to build to `esnext` then make use of https://github.com/s-panferov/awesome-typescript-loader#usebabel-boolean-defaultfalse to compile to ES5 safe javascript

**Comment by will-byrne** [comment]
We will still need this for testing full pages and the application as a whole. Storybook is great for the component level but not good for checking navigation and page layout. 

It might be best to remove it and have good docs for adding it to test locally.
