### ISSUE TITLE
Create a package of auth interfaces

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#205]
This should then be used by any implemented server and/or client that uses auth data.

**Comment by erezmus** [comment]
in lib/auth-utils, we have UserIdentity. Do we need anything else as well? The only other thing I can see is the JournalAuthToken interface defined in continuum-auth/src/jwt.s

/cc @diversemix

**Comment by diversemix** [comment]
@erezmus  ... TBH not sure what this ticket is about. The "interface" is the contents of the token - we will eventually need a users roles in there as well but that can come later - i.e. after Parity

**Comment by erezmus** [comment]
I think we should close this

/cc @diversemix
