### ISSUE TITLE
Investigate & decide how to do end2end tests

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#208]
We need tests for `libero-reviewer` separate from those of `elife-reviewer` - do these tests live in their own repo?

The mock auth service should be used for `libero-reviewer` and the mock profiles service used for the elife implementation.

Do we re-use them from elife-xpub? or write new ones?

/cc @Cooryd @will-byrne @erezmus @petereast

**Comment by giorgiosironi** [comment]
Maybe take the opportunity to find a precise name for the scope that these tests cover, which can go from integrating client and server of a React app to full-scale integration with the rest of Libero products.

**Comment by giorgiosironi** [comment]
Options for scope:
- `client` and `server`
- all Libero Reviewer modules
- all Libero products
- Libero Reviewer modules plus Continuum

Everything not included possibly needs stubbing.

Infrastructure options:
- Libero
- eLife (mandatory if Continuum is included)

**Comment by diversemix** [comment]
Can we close this now @will-byrne

**Comment by giorgiosironi** [comment]
> Maybe take the opportunity to find a precise name

To be renamed to `integration tests`, and closed?

**Comment by diversemix** [comment]
https://github.com/elifesciences/issues/issues/5519

**Comment by diversemix** [comment]
End2end tests will be eLife specific and rely on elife services (such as journal and profile service)
