### ISSUE TITLE
PUBSWEET TYPES

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#211]
This relates to !abstractions in pubsweet

See https://gitlab.coko.foundation/pubsweet/pubsweet/merge_requests/593

https://gitlab.coko.foundation/pubsweet/pubsweet/issues/461

**Comment by diversemix** [comment]
@petereast ... not sure that the message queue stuff should be going in as part of this MR?

**Comment by petereast** [comment]
This is waiting for review in pubsweet's gitlab

**Comment by petereast** [comment]
To be continued... #221
