### ISSUE TITLE
Create a MANUSCRIPT_UPLOAD component

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer#218]
Still need to flesh out the config for this (remember to update the elife config file). This component should consist of the main manuscript upload and if the config options are provided, the supporting document upload. File size options ect. should be passed as config and all text should be imported form translation files. Translation keys should be overridable through config.

```
{
    id: 'manuscriptFile',
    type: 'MANUSCRIPT_UPLOAD',
    options: {
        validation: true,
        supportingFiles: {
            id: 'supportingFiles',
            options: {
                // What should be configurable here? fileSize?
            },
        },
        //What should be configurable here? fileSize?
    },
},
```

validation option should just be a boolean and toggle xpubs validation ie: supporting only show if manuscript has been uploaded. manuscript required.

In future, this component might be split into two field types PRIMARY_UPLOAD and SUPPORTING_UPLOAD so try to keep components well separated. For this though it'll be easier to keep as a single component.

<img width="839" alt="Screenshot 2019-09-10 at 14 12 15" src="https://user-images.githubusercontent.com/22455561/64616837-3ad45700-d3d5-11e9-8c66-a68c50207dd8.png">

**Comment by erezmus** [comment]
Closed via #293
