### ISSUE TITLE
Expose the yarn cache to travisci

### ISSUE THREAD

**Issue by petereast** [libero/reviewer#257]
This should significantly speed up builds in travis-ci.

We can do this  by mounting the yarn cache to an external folder in `docker-compose.build.yml` and then directing the [travis cache](https://docs.travis-ci.com/user/caching/#caching-directories-bundler-dependencies) to the mounted volume

**Comment by giorgiosironi** [comment]
Assuming yarn commands run inside Dockerfiles, not understanding if [build-time volumes](https://github.com/moby/moby/issues/14080#issuecomment-484314314) are allowed in Docker now, as historically they weren't due to reproducibility issues.
