### ISSUE TITLE
Make the `event-bus` lib configurable

### ISSUE THREAD

**Issue by petereast** [libero/reviewer#264]
Currently you can't configure anything in the message queue. This is bad. We need to make the following things configurable: 
- `RABBIT_URL` - this will contain all the information about connecting to the server: `amqp://...`

**Comment by nlisgo** [comment]
This issue was created before the work done in https://github.com/libero/reviewer/pull/397

Can we consider this issue done or is further work needed?

**Comment by diversemix** [comment]
I think that #402 is pretty much the last thing left to do - so happy if this gets closed out in-lieu of that 
/cc @erezmus

**Comment by erezmus** [comment]
This is already done
