### ISSUE TITLE
Improve Submission Wizard

### ISSUE THREAD

**Issue by petereast** [libero/reviewer#31]
There are a few things left to do in the mini 'submission wizard':

- [ ] **M** Have more fields in it
- [ ] **M** Use configurable SASS/SCSS classes instead of inline `style` attributes
- [ ] **M** Move the 'saving/unsaved/validation' logic out of the component and into helper function(s)
- [ ] **S** Refactor the form to have levels of state (i.e. consolidate the form state)
- [ ] **M** There **must** be some other stuff... ( ͡° ͜ʖ ͡°)
- [ ] **C** Implement AutoSave

**Comment by diversemix** [comment]
out-of-date
