### ISSUE TITLE
Update elife submission form config to match defined requirments

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer#320]
Following the meeting on initial submission form customisation we should update the elife config file to match the newly defined spec for what should / shouldn't be configurable.

**Comment by Cooryd** [comment]
We need to think about where we will store / retrieve Article types and Subject Areas. Publishers should be able to update these in one place and they will need to be accessible to the back end and front end in some way. Putting them in the form config json doesn't seem right.

**Comment by erezmus** [comment]
is there a link to the spec?
