### ISSUE TITLE
Fix new relic errors not being shown

### ISSUE THREAD

**Issue by erezmus** [libero/reviewer#354]
Followup on libero reviewer from https://github.com/elifesciences/elife-xpub/issues/2254.

- [x]  In order to fix react js error "maximum update depth exceeded" on xpub, we need to fix the front end errors not appearing on new relic browser product
- [ ] We also need to see a full stack trace

**Comment by erezmus** [comment]
From investigation on 7/11/2019:
- Was able to upload a source map file when throwing an Error from a component.
- However, when an error was generated through a render loop, it was not possible. This is probably due to the fact that the react source is minified
- I tried again with NODE_ENV=development, but that didn't seem to change anything (this might be because we are using hot reloading...)

Next step:
- Try in the new reviewer client to report a render loop error with development version of react

**Comment by erkannt** [comment]
Closing in hope that our production release doesn't have this issue.
