### ISSUE TITLE
Investigate client tests attempting to connect to 127.0.0.1:80

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer#367]
see: #364 for context.

We fixed client tests throwing connection errors in PR #366  by changing the `setImmediate` to `setTimeout` in out flushPromises function. While this fixes the issue it would be useful to understand why the tests were attempting to connect to our local port 80 and to see if theres anything we can do to fix it / raise issues on whatever package may be causing this.

Reproduce error:

change https://github.com/libero/reviewer/blob/317be6cdf33c59975ad49a4b864a8b8c131e5374/client/test-utils/flushPromises.ts#L3 to `setImmediate` and run `yarn test` over https://github.com/libero/reviewer/blob/master/client/src/ui/molecules/ManuscriptUpload.test.tsx

**Comment by diversemix** [comment]
It fails for me too :cry:

**Comment by will-byrne** [comment]
It seems to be a timing issue due to the way the JS event loop works, there is a good explanation here [on the differences between `setImmediate` and `setTimeout`](http://voidcanvas.com/setimmediate-vs-nexttick-vs-settimeout/)

**Comment by diversemix** [comment]
One additional note the erro is coming from the `virtual-console` code so  (we think) this is why there is a connection to localhost
