### ISSUE TITLE
Add string templating to internationalisation translations 

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer#373]
We're currently having to store multiple string fragments as translations when working with variables (see: https://github.com/libero/reviewer/blob/83d45e624c41ee78b53bba4372a1f8d4d411a2b6/client/src/ui/molecules/PeoplePickerSelector.tsx#L87-L89). This doesn't work well with true translations where sentence structure may change and is also messy to maintain.

We should look into https://www.i18next.com/translation-function/interpolation as a way to pass params to our translation functions.

**Comment by diversemix** [comment]
We have it in .... makin Internationalization a feature is for a later date.
