### ISSUE TITLE
Investigate how should step based auto saves work client -> server

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer#386]
We need to decide how we will be doing autosaves with the step based wizard. Previously we were sending over the whole form on auto save which caused some issue with validation. We have the chance to improve how we are handling the data between client and server when saving so we should look through out options.

- full form data save
- step data save
- changed data save

**Comment by diversemix** [comment]
Should we now close this?
/cc @hdrury1 @Cooryd
