### ISSUE TITLE
embed data studio report in review author instructions page

### ISSUE THREAD

**Issue by hdrury1** [libero/reviewer#388]
The [ejp authors instruction metrics page](https://submit.elifesciences.org/html/elife_author_instructions.html#metrics)'s chart now uses embed data studio report. 
## Subtasks

- [ ] Replicate this report embedding in the[ libero reviewers authors guide page](https://reviewer.elifesciences.org/author-guide/journal-metrics)
Information on the embedding for each chart can be found on the [ejp authors instruction metrics page](https://submit.elifesciences.org/html/elife_author_instructions.html#metrics) 
/cc @hdrury1  @Milly-eLife @mariajoaoguerreiro

**Comment by mariajoaoguerreiro** [comment]
Hello @erezmus and @hdrury1 I see that you've closed this issue, but it seems that the text and charts on Reviewer have not yet been updated (https://reviewer.elifesciences.org/author-guide/journal-metrics). Can you let me know if this will update shortly? Thanks!

**Comment by erezmus** [comment]
I can see it has passed the test pipeline, so will probably be live tomorrow.

https://alfred.elifesciences.org/blue/organizations/jenkins/test-elife-xpub/detail/test-elife-xpub/1094/pipeline

@hdrury1 do we need to keep this ticket open until its on production?

**Comment by diversemix** [comment]
@mariajoaoguerreiro ... there is also an ongoing issue for the deployments. I think this ticket should be closed as the work has been done. But this is an unusual situation - as its going to take a while to deploy to production - but please keep on chasing if its not there in the next few days.
