### ISSUE TITLE
Move client related docs

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer#394]
As part of the move away from monorepo we need to move any related docs from reviewer to reviewer-client. This might mean adding to these to make clear what other repos contain the services needed to run the app correctly.

**Comment by will-byrne** [comment]
We need to add a section in a dev doc for the githooks and how to bypass them:

We use Husky for pre-commit and pre-push hooks, pre-commit will run the linter and pre-push will run the unit tests. If these need to be bypassed use `HUSKY_SKIP_HOOKS=1 git commit....`.
