### ISSUE TITLE
Configure travis to run pipeline over reviewer-client

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer#401]
Once the new Make file is in place in the reviewer-client repo we should create a `.travis.yml` file and get a working pipeline running on PRs.

**Comment by Cooryd** [comment]
Docker Hub and AWS credentials will need to be set up within Travis UI for the repo too.

**Comment by giorgiosironi** [comment]
[Full list](https://travis-ci.com/libero/reviewer/settings):
```
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
DOCKER_PASSWORD
DOCKER_USERNAME
GITHUB_TOKEN
```
Probably all of them.

**Comment by hdrury1** [comment]
Un-assigning Cory given he'll be off this week.

**Comment by giorgiosironi** [comment]
`DOCKER_*`: https://github.com/elifesciences/it-admin/blob/master/libero.md#docker-hub
`GITHUB_TOKEN`: needs to be generated by logging in with https://github.com/elifesciences/it-admin/blob/master/libero.md#docker-hub, look at the existing tokens scope to copy it.
`AWS_*`: need to log in with https://github.com/elifesciences/it-admin/blob/master/libero.md#docker-hub and get a AWS user. There should already be an existing one for Travis CI, but not sure if we can find out if we stored the credentials somewhere retrievable.

**Comment by giorgiosironi** [comment]
The AWS user is https://console.aws.amazon.com/iam/home?region=us-east-1#/users/unstable-reviewer-travis-ci so the credentials are in `terraform output` that @erezmus should be able to run now. 

We could create another user there but it's probably overkill to do this for every single repository as opposed to every product?

**Comment by diversemix** [comment]
I've created an docker hub "Access Token" for the build - 

@giorgiosironi ... I think this is probably more scalable than using username / password combo. ref: https://docs.docker.com/registry/spec/auth/token/#how-to-authenticate

**Comment by giorgiosironi** [comment]
Yes, is there a good UI or CLI to manage the Docker Hub tokens?
