### ISSUE TITLE
Login page layout broken

### ISSUE THREAD

**Issue by hdrury1** [libero/reviewer#415]
XPUB PRODUCTION BUG: Between 768 and 1000 pixels the illustration on the login page is falling below the text. I think the quickest fix is to hide the image at viewports below 1000px.

![20191020_080920](https://user-images.githubusercontent.com/17023702/67185345-810dd480-f3dd-11e9-8771-799c521f6e94.jpg)

**Comment by chugginselifesciences** [comment]
https://invis.io/SQT9JBWXKG8#/376258686_login-768px
