### ISSUE TITLE
Prod deployment failure

### ISSUE THREAD

**Issue by hdrury1** [libero/reviewer#416]
Should be addressed to ensure we can deploy fix to #415 

https://alfred.elifesciences.org/blue/organizations/jenkins/prod-elife-xpub/detail/prod-elife-xpub/300/pipeline

**Comment by giorgiosironi** [comment]
Solved in https://alfred.elifesciences.org/job/prod-elife-xpub/301/console through https://github.com/elifesciences/issues/issues/5137
