### ISSUE TITLE
Provisioning of service databases

### ISSUE THREAD

**Issue by erezmus** [libero/reviewer#423]
Now that we have common migrator package, we need to think about how we get any databases needed created in the first instance.

The central question is whether the service should assume that the database is present already or should it be part of its migration process?

If the former, then it should be an infrastructure concern. If the latter, then it will probably not be possible to do it as part of a migration as we need to store the state of the migrations in a table, which needs a database. A special script would need to be created.

/cc @giorgiosironi

**Comment by giorgiosironi** [comment]
My understanding is a logical database exists, either because it is created by a `postgres` container or as part of the RDS infrastructure setup for managed ones.
This being `postgres`, assume also a `public` schema inside that database. No tables exist at creation time however.

**Comment by erezmus** [comment]
What we could do is have setup.sh script that creates all the necessary databases?

/cc @diversemix

**Comment by diversemix** [comment]
@erezmus yeah - I was thinking the same thing ... we could add it to the make file?

**Comment by erezmus** [comment]
Well we would need to maybe get the database name from the .env file. Is that possible in an Makefile?

**Comment by giorgiosironi** [comment]
You can `source .env` in any bash script but just posted that a script to create database should not be needed in any environment?

**Comment by erezmus** [comment]
I would imagine it would be for local development only.

**Comment by giorgiosironi** [comment]
https://hub.docker.com/_/postgres creates a default database named via the `POSTGRES_DB` environment variable, isn't that usable?

**Comment by erezmus** [comment]
possibly, although we are going for multiple databases but i guess we could use same one for local environment.

**Comment by erezmus** [comment]
Now that we are further along development and started to set up the staging environment, i'm currently reviewing situation and after talking with @diversemix, there are a few related issues that i'll list here:

- We need a way of creating the needed databases for each service for local development
- On staging k8s cluster, we currently have a postgres database that is used by the submission service and is not persisted. We eventually want to move to an external RDS service to mirror production.
- We will probably need provisioning in builder to set up the databases for production and staging
- During integration and end to end tests those databases will also need to be set up then destroyed (elife specific)
- We will want to have separate read and write users (see #433)
- We need to document the options for provisioning databases

/cc @giorgiosironi

**Comment by giorgiosironi** [comment]
> We need a way of creating the needed databases for each service for local development

Not much indication on how to do this in development, but the `postgres` containers should create a logical database on startup which can then host tables coming from a migration script.

> On staging k8s cluster, we currently have a postgres database that is used by the submission service and is not persisted. We eventually want to move to an external RDS service to mirror production.
> We will probably need provisioning in builder to set up the databases for production and staging

Yes, this will be under a `libero-reviewer` project with a configuration similar to https://github.com/elifesciences/builder/blob/master/projects/elife.yaml#L1842-L1848 but no EC2 instances.

> During integration and end to end tests those databases will also need to be set up then destroyed (elife specific)

Not really, if you have a migration script you want this to run on an existing database to check it works on realistic state before it goes in `prod`. So `end2end` and `staging` typically run a cleanup daily in the morning, but not on each build so as to leave some buildup of data.

> We will want to have separate read and write users (see #433)

Anything more than the pseudo-`root` user that RDS creates automatically is a [wicked problem](https://github.com/elifesciences/issues/issues/4381) to setup as the instance is behind firewalls and can't be accessed through Terraform-from-a-laptop. I'd like some threat modeling to result in how many database users we should have.

> We need to document the options for provisioning databases

As in RDS vs containers?

**Comment by erezmus** [comment]
> > We need a way of creating the needed databases for each service for local development
> 
> Not much indication on how to do this in development, but the `postgres` containers should create a logical database on startup which can then host tables coming from a migration script.
> 
For local development, we'll probably use multiple databases so default one won't be sufficient.

> > On staging k8s cluster, we currently have a postgres database that is used by the submission service and is not persisted. We eventually want to move to an external RDS service to mirror production.
> > We will probably need provisioning in builder to set up the databases for production and staging
> 
> Yes, this will be under a `libero-reviewer` project with a configuration similar to https://github.com/elifesciences/builder/blob/master/projects/elife.yaml#L1842-L1848 but no EC2 instances.
> 
Agreed

> > During integration and end to end tests those databases will also need to be set up then destroyed (elife specific)
> 
> Not really, if you have a migration script you want this to run on an existing database to check it works on realistic state before it goes in `prod`. So `end2end` and `staging` typically run a cleanup daily in the morning, but not on each build so as to leave some buildup of data.
> 
Agreed
> > We will want to have separate read and write users (see #433)
> 
> Anything more than the pseudo-`root` user that RDS creates automatically is a [wicked problem](https://github.com/elifesciences/issues/issues/4381) to setup as the instance is behind firewalls and can't be accessed through Terraform-from-a-laptop. I'd like some threat modeling to result in how many database users we should have.
> 
Understood

> > We need to document the options for provisioning databases
> 
> As in RDS vs containers?
I was thinking external to k8s cluster and within k8s cluster (via a postgresql k8s deployment and service)

**Comment by giorgiosironi** [comment]
> For local development, we'll probably use multiple databases so default one won't be sufficient.

Multiple containers for each database? That is an environment that is more similar to reality.

> I was thinking external to k8s cluster and within k8s cluster (via a postgresql k8s deployment and service)

Yes talking about the same thing.

**Comment by erkannt** [comment]
Obsolete due to no longer using shared libero services.
