### ISSUE TITLE
Update audit schema and storage of events

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#427]
## Database schema

Change the schema for the audit table to:
- entity (string)
- action (string)
- object (string)
- date (timestamp)

## Functionality
- Change the service started to use the Logger rather than inserting it as an audit event
- Change the storage of audit events to reflect new schema.
### Examples: 
User logs in
  * entity: user:<user-uuid>
  * action: 'LOGGED_IN'
  * object: 'application'

User approves manuscript
  * entity: user:<user-uuid>
  * action: 'APPROVES'
  * object: 'manuscript:<manuscript-uuid>'

**Comment by erezmus** [comment]
Moved separate database user to #433
