### ISSUE TITLE
Create a Loading Spinner component

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer#445]
xpub has an animated spinner used to show the loading state of any gql requests. We are currently using a loading string on the dashboard when fetching data. We should create a `Spinner` component and use this instead of the string output.

https://github.com/libero/reviewer-client/blob/c3b48f2e27a14a9ff2f6ef44a0e2f9b090b496be/src/dashboard/components/Dashboard.tsx#L21

**Comment by diversemix** [comment]
Part of #603
