### ISSUE TITLE
Replace use of curl for container health checks

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer#525]
currently we're using `curl` to check the health of containers configured in the docker-compose file. `curl `isn't available on all containers by default so many are being listed as in an `unhealthy` state when they are working correctly. Instead of making this a requirement for all images, we can use the following instead (with port variable and default set as required):

`'echo -e "GET /health\n\n" | nc localhost ${SERVICE_PORT_VARIABLE:-3001}'`

just one example: https://github.com/libero/reviewer/blob/06e0bd077364b3633d81238383b8685cd18b2c8c/docker-compose.yml#L42

**Comment by diversemix** [comment]
duplicate of #562
