### ISSUE TITLE
Raise an ADR for our choice of Nest.js

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#527]
We need to revisit our choice of Nest.js in the light of the amount of boiler plate code and catch-throw code that we need to add.

Publisher has gone for Koa (rather than express see: https://github.com/koajs/koa/blob/master/docs/koa-vs-express.md)

It would be good to:
- [ ] Validate our decision of Nest.js
- [ ] Understand why Koa is the choice for Publisher.
- [ ] Ensure future Libero components/products follow a similar decision tree.

**Comment by diversemix** [comment]
Placeholder not urgent for discussion:

/cc @norisalsaadie @erezmus @giorgiosironi @thewilkybarkid

**Comment by erezmus** [comment]
Added https://github.com/libero/community/issues/34

**Comment by erezmus** [comment]
@diversemix can we close this?
