### ISSUE TITLE
Implement the necessary migrations to have the xPub Schema in the database

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#535]
We've agreed (informally) that for ease of deployment we are going with the legacy database schema in xPub ( [refer to documentation](https://github.com/elifesciences/elife-xpub/blob/5e3ab0792deba552d0351b4792a20e1eccf53132/docs/developing/migrations.md) )

There are quite a few migrations in the repo:
```
./packages/component-model/migrations/1545390290-alter-audit-log.sql
./packages/component-model/migrations/1536842027-opposed-reviewers.sql
./packages/component-model/migrations/1562838080-survey-response.sql
./packages/component-model/migrations/1533830042-elife.sql
./packages/component-model/migrations/1551872573-semantic-extraction.sql
./packages/component-model/migrations/1542896967-alter-manuscript.sql
./packages/component-model/migrations/1540916414-meta-json.sql
./packages/component-model/migrations/1534492669-nullable-journal.sql
./packages/component-model/migrations/1551788192-alter-type-audit-log.sql
./packages/component-model/migrations/1545231292-remove-suggestions-confict-manuscript.sql
./packages/component-model/migrations/1533672892-initial.sql
./packages/component-model/migrations/1548236987-filestatus.sql
./packages/component-model/migrations/1562916541-survey-updated.sql
./packages/component-model/migrations/1548324802-alter-audit-log.sql
./packages/component-meca/migrations/1538487310-ejp-name.sql
```

I suggest just using the existing schema in production - attached below.

[xpub-schema.zip](https://github.com/libero/reviewer/files/4127532/xpub-schema.zip)

**Comment by erezmus** [comment]
Notes on 
* `audit_log` is already done, but we changed the schema, are we keeping the data from xpub or migrating it?
* `ejp_name`: this seems to be used in meca export, but i don't think we ever insert anything into it
* `entities`: don't think this is used
* `file`: move to storage service ?
* `identity`: already in continuum-adaptor
* `journal`: don't think this is used
* `manuscript`: should go in the submission service
* `migrations`: not needed as we are starting over and anyways each database will have its own migrations table
* `organization`: don't think this is used
* `review`: don't think this is used
* `semantic_extraction`: should go in submission service
* `survey_response`: should go in submission service
* `team`: should go in submission service
* `user`: already in continuum-adaptor

**Comment by erezmus** [comment]
we should also write scripts to move the data from xpub to each destination database

**Comment by diversemix** [comment]
Ok ... perhaps we should discuss keeping it all in one database for the initial release vs. doing the split into databases now.

I think my preference is to try and de-risk the issues with data by using "exactly" the same schema - so we can just deploy ontop of the exiting database. Happy to discuss if people think this is a bad idea.

/cc @hdrury1

**Comment by erezmus** [comment]
its possible and would make deployment easier as we don't have to provision databases, but it means we need to move existing migrations in continuum-adaptor and audit into one service (submission?). No t a big job though.

**Comment by giorgiosironi** [comment]
> try and de-risk the issues with data by using "exactly" the same schema

I think this depends on how you want to migrate later. You want to write code in the application to write to two different schemas at the same time (kind of Branch by Abstraction)? Or stopping the engines, execute a (well tested) migration bringing data from one database into the others, starting engines again?

Migration windows with downtime are allowed, we did so even for elifesciences.org in extreme cases. But big bang migrations are inherently risky so they have to be executed over and over as a test, before the final one when the switch is made.

From an infrastructure point of view, you should try connecting to the existing running RDS database through a temporary Pod created via `kubectl run`. No idea if the networking is set up correctly to allow this to happen smoothly.
