### ISSUE TITLE
How do we test / validate our GraphQL?

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#538]
Seems to me we need to have coherency across:
* GraphQL schema in submission-reviewer - src/schemas/submission.graphql
* Code implementation (resolvers) in submission-reviewer - src/resolvers/submission.ts
* GraphQL schema in reviewer-mocks : src/mock-graphql/typeDefs.ts`
* Code implementation in reviewer-mocks - src/use-cases/startSubmission.ts
* Schema in reviewer-client src/dashboard/graphql.ts

Things to consider:

* https://github.com/APIs-guru/graphql-faker
* https://github.com/apollographql/eslint-plugin-graphql
* https://github.com/cjoudrey/graphql-schema-linter

**Comment by norisalsaadie** [comment]
Consider these items around security https://blog.apollographql.com/securing-your-graphql-api-from-malicious-queries-16130a324a6b

**Comment by norisalsaadie** [comment]
read:
- https://medium.com/@localh0t/discovering-graphql-endpoints-and-sqli-vulnerabilities-5d39f26cea2e
- https://redux.js.org/recipes/server-rendering#security-considerations

**Comment by norisalsaadie** [comment]
Validating client schemas:

1. Validating schemas on the client is less than ideal. A solution is outlined here https://cbranch101.github.io/scrimshaw-react/docs/linting-graphql.html - this requires the client to fetch the schema from the server over introspection.

2. Schemas could be a gitsubmodule but this can be hard to manage

**Comment by norisalsaadie** [comment]
Validating server schemas:

Already achieve as per reviewer-submission repo

**Comment by norisalsaadie** [comment]
When required to limit input range use https://github.com/joonhocho/graphql-input-number

**Comment by norisalsaadie** [comment]
Closed in favour of specific tickets
