### ISSUE TITLE
Modal version of author guide

### ISSUE THREAD

**Issue by hdrury1** [libero/reviewer#543]
# See Comment
_As an author, I would like to be able to access the author guide during my submission when I require additional information._

_As an author, I would like to be able to easily return to where I left off in my submission in order to minimise the time spent submitting my research._

We would like to implement a modal version of the author guide that can be accessed via various links embedded within the submission wizard. An author should be able to access the guide from the wizard, but also seamlessly return to their previous place in the wizard in a single step without losing any work.

![Screenshot (2)](https://user-images.githubusercontent.com/17023702/75680350-51bf7c00-5c89-11ea-8e70-e865f7a50e53.png)

**Comment by diversemix** [comment]
Only do the Routes pre-release - build with knowledge that its to be used in a modal later

**Comment by diversemix** [comment]
Parking this improvement in favour of releasing sooner
