### ISSUE TITLE
Reviewer diversity text

### ISSUE THREAD

**Issue by hdrury1** [libero/reviewer#545]
_As an editor I want to ensure that I am inviting reviewers from a wide pool to avoid implicit bias_

_As a member of eLife staff I want to promote policies of diversity amongst reviewers to encourage responsible behaviours in science_

Add a link to the author guide and encourage submitting authors to consider reviewer diversity when suggesting experts to review their work.

**Comment by hdrury1** [comment]
![image](https://user-images.githubusercontent.com/17023702/78659918-13d6f880-78c4-11ea-8067-d8c077ee8d69.png)

**Comment by chugginselifesciences** [comment]
Worth noting this ticket (possibly) refers to both the link in the wizard and the content in the Author guide it links to. I can't check staging right now to see if its in there already, but couldn't find a separate ticket. The text is currently in xPub and eJP though. (In Initial Submissions text)

> 7. Reviewer suggestions: Authors can optionally suggest potential reviewers for their work at the Initial Submission stage. Please list the names of experts who are knowledgeable in your area and could give an unbiased review of your work. To support diversity, please consider suggesting potential reviewers at an early stage of their career, women, and experts from countries other than the USA and Europe. Please do not list colleagues who are close associates, collaborators, or family members. Requests to exclude individuals can also be made and must be accompanied with a brief explanation. We will make every effort to follow author requests for excluded individuals.
