### ISSUE TITLE
Move production checks into Reviewer Reporter - Part 1

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#547]
The current script that emails `scripts/prod-status.sh` is ran locally on my machine for expediency - move this to New Relic.

## The Plan
- [x] Create a new repo `reviewer-reporter` - this will initially publish a container that will send stock emails at 8am and 1pm daily.
- [x] Add github actions to allow the image to get pushed to docker.
- [x] Make changes to elife-xpub-formula to enable this to get deployed into production.
- [x] Make changes to elife-xpub-deployment to enable this to get deployed into production.

Part 2 - is to actually add the scripts that do the reporting into the new repo and deploy so that the functionality is complete.

**Comment by giorgiosironi** [comment]
In Synthetics (if it can be made HTTP-accessible)? https://synthetics.newrelic.com/accounts/1451451/monitors

**Comment by diversemix** [comment]
@BlueReZZ / @giorgiosironi 
> Self service of Synthetics trials is temporarily disabled. To start a 14 day trial and begin using advanced monitors, please contact sales. At the end of your trial period all advanced monitors will be disabled.

What is the feeling about paying for this? Meanwhile I will continue with the docker container to handle reporting.

**Comment by giorgiosironi** [comment]
Synthetics are binary checks that should be on/off, this is a reporting need so a cron serves it better than making New Relic ping a script every hour.

**Comment by diversemix** [comment]
> Synthetics are binary checks that should have a red/green result, this is a reporting need so a cron serves it better than making New Relic ping a script every hour.

Ok ... also its not as binary as red/green there is a lot of interpretation that needs to go on.

**Comment by BlueReZZ** [comment]
Even the paid for version of synthetics only gives you a limited amount of scripting, and it's very hard to version control/deploy to it (last time I used it we just copy/pasted) so anything more than a couple of lines is hard to manage.

In short, if you need to logic to interpret the results, and can't encapsulate that in the HTTP response, then something else might be better.

If you think different though, I'm happy to pay.

**Comment by diversemix** [comment]
Deployed
