### ISSUE TITLE
Add end to end test

### ISSUE THREAD

**Issue by erezmus** [libero/reviewer#551]
Add a test that tests the login function using all the services with reviewer-mocks mocking the journal

This would provide some assurance that all the service are working together before pushing to staging

**Comment by diversemix** [comment]
@hdrury1 I'd like to move this into ToDo ASAP ... what do you think?

**Comment by giorgiosironi** [comment]
This influences https://github.com/elifesciences/issues/issues/5482, when can we design this together? Given the description, assuming these run on Libero infrastructure.

**Comment by erezmus** [comment]
@giorgiosironi i can do tomorrow sometime

**Comment by giorgiosironi** [comment]
Calendars please

**Comment by erezmus** [comment]
@diversemix  and @Cooryd are working on this now. Please update with any new info
