### ISSUE TITLE
Ensure we are no longer using liberoadmin for docker hub

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#552]
The use of `liberoadmin` was temporary and should now be removed.

Check and change throughout all the repos.

**Comment by erezmus** [comment]
do we own the libero name now on docker hub?

**Comment by giorgiosironi** [comment]
No, but the use of `liberoadmin` should be encapsulated to https://github.com/libero/scripts/blob/master/github/push-image.sh#L12 so that we can change it later.

**Comment by erkannt** [comment]
Closing as we still don't own libero
