### ISSUE TITLE
Correct the text representations of article types	bug

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#589]
The text representations should be:

```
 "feature"
 "scientific-correspondence"
 "research-article"
 "tools-resources"
 "short-report"
```

Cloned from libero/reviewer-submission/issues/103

**Comment by erezmus** [comment]
Currently we have in reviewer-submission?
```
export enum ArticleType {
    RESEARCH_ARTICLE = 'researchArticle',
    FEATURE_ARTICLE = 'featureArticle',
    RESEARCH_ADVANCE = 'researchAdvance',
```
Is featureArticle now just "feature" ? what about the other ones?

**Comment by diversemix** [comment]
1) yes - "feature" is feature article"
2) researchArticle should be "research-article" (see explanation)
3) researchAdvance - I suggest is "research-advance" - although this matters less as there are no articles of this type in the database.

**Comment by erezmus** [comment]
but do i add  "scientific-correspondence",  "tools-resources", "short-report" ???

or do i just change to snake case ?

**Comment by diversemix** [comment]
Finished with https://github.com/libero/reviewer-client/pull/160
