### ISSUE TITLE
Display server side validation of the submission

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#604]
Any errors to be shown in the dangly-bar - TBC

/cc @chugginselifesciences

**Comment by diversemix** [comment]
The main code for this went in as part of https://github.com/libero/reviewer-submission/pull/122 ... leaving this open to mop up the validation at the end of the milestone.

**Comment by hdrury1** [comment]
Look at implementing this in the simplest way possible initially.

**Comment by erkannt** [comment]
Backend and frontend validation are separate beasts. So they might drift by accident. User somehow needs to be informed how to fix any issues identified by the server side validation.

**Comment by erkannt** [comment]
Result of discussion with @hdrury1 and @norisalsaadie:

- if server side validation fails we only tell the user that something went wrong and we are looking into it
- instructing the user how to fix it is a potential post-release task

**Comment by norisalsaadie** [comment]
Closed as per https://github.com/libero/reviewer-client/pull/339
