### ISSUE TITLE
Add sciencebeam to deployment

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#615]
Ensure that sciencebeam is deployed as part of reviewer

**Comment by erkannt** [comment]
Deployed on test cluster using the chart from [elifesciences/sciencebeam-charts](https://github.com/elifesciences/sciencebeam-charts).

https://sciencebeam--prod--test-cluster.elifesciences.org/api/convert

It is a separate release from `reviewer` as I can't add a git repo as a chart dependency.

**Comment by erkannt** [comment]
Reopening to address:

- deploy without ingress, internal only
- default port, route etc
- look into ways to get it as a subchart/requirement

**Comment by erkannt** [comment]
- public deploy will be left intact until we remove the formula based staging
- reviewer is now pointed at the internal service instead of the external url
- might revisit integrating sciencebeam as subchart after release
