### ISSUE TITLE
Extract title with sciencebeam

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#616]
When a manuscript is uploaded call to sciencebeam and populate the suggestions - as per xPub

See https://github.com/elifesciences/elife-xpub/blob/48f40da3887f7c2129bac0f93f1795976f0e5295/packages/component-submission/server/services/scienceBeamApi.js

**Comment by diversemix** [comment]
@norisalsaadie / @erezmus ... I can see this code in the codebase - is there anything still left to do?

**Comment by norisalsaadie** [comment]
The code is the there https://github.com/libero/reviewer-submission/blob/master/src/domain/semantic-extraction/services/semantic-extraction-service.ts#L23 

Need to make sure it's hitting the right server(s)

**Comment by erezmus** [comment]
also need to update reviewer-mocks
