### ISSUE TITLE
Use the suggested title to pre-populate the title field

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#617]
Breakdown of work

- [x] Update mock to complete the suggestion object of the submission after manuscript upload
- [ ] Update the client to use the suggestion attribute of the submission on the details page
- [ ] Check what currently exists on the server with regard to sciencebeam / suggestions, complete what is missing

**Comment by norisalsaadie** [comment]
After a short investigation based on xpub, this seems to be client-side based. 

Server is only adding to suggestion array: https://github.com/elifesciences/elife-xpub/blob/49a5cc6efd6a240fc180646c25e20522d3354c08/packages/component-submission/server/use-cases/helpers/manuscript.js#L72

Client is setting the title: https://github.com/elifesciences/elife-xpub/blob/de9c463384a7354bd31c0bf6b7adaf79e70ee874/packages/component-submission/client/pages/FilesStepPage.js#L69-L78

**Comment by erezmus** [comment]
Can anybody remember why we set the title in the client on xpub? @diversemix @Cooryd @will-byrne

**Comment by diversemix** [comment]
So the user doesn't have to fill out the field
