### ISSUE TITLE
add mutation for saveDetailsPage

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#620]

**Comment by diversemix** [comment]
Start by renaming the exsiting `saveDetailsPage` to `saveAuthorPage`

**Comment by diversemix** [comment]
Committed some changes - but we've spent a long time talking about some critical design decision on the server side.... unassigning and creating a new ticket

**Comment by Cooryd** [comment]
This should probably address this too https://github.com/libero/reviewer/issues/663
