### ISSUE TITLE
Add the Survey Page

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#624]
Ask questions as per xPub

**Comment by Cooryd** [comment]
<img width="1680" alt="Screenshot 2020-06-18 at 09 32 37" src="https://user-images.githubusercontent.com/22455561/84997893-0604e580-b147-11ea-9c5c-e9a63aa265c2.png">
<img width="1680" alt="Screenshot 2020-06-18 at 09 32 47" src="https://user-images.githubusercontent.com/22455561/84997898-07cea900-b147-11ea-844a-edb321ff312f.png">
