### ISSUE TITLE
Add Thank you page

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#626]
as per xPub

**Comment by Cooryd** [comment]
<img width="1680" alt="Screenshot 2020-06-18 at 09 32 59" src="https://user-images.githubusercontent.com/22455561/84997709-d5bd4700-b146-11ea-9139-08bf33d659ec.png">

**Comment by Cooryd** [comment]
Ignore the hotjar feedback widget in the bottom right (that's on every page in prod)
.
