### ISSUE TITLE
Server-side design decisions

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#629]
Discover the outstanding questions to resolve about using "Submission" 

### Background

As part of #620 it was becoming apparent that the implementation was catalyzing some rather major changes to the code. These changes were not entirely obvious they were fitting in with the intended design. At this point we had a meeting and spent a while talking about options. There was not clear agreement as to the way forward - largely because it was not obvious. Hence the issue

**Comment by diversemix** [comment]
### Use-Case
Save the manuscript details

- The `saveDetailsPage` Resolver calls the Wizard Application Service.  This checks permissions, then
- calls `saveManuscriptDetails` on the Submission Domain Service

The following questions arise about how this should be handled at this point down to the repository and the return of the entire Submission. These questions arise from the fact that the domain concept of a Submission is spread around many tables in the database and are based around how best to handle this.

**Comment by diversemix** [comment]
### Questions
- **Premise** : The `SubmissionDTO` contain all possible values (e.g. Files) for a Submission regardless of which tables they are stored in the database. The SubmissionDTO does not contain any behaviour, this is defined on the `Submission` Domain Object.
1. **The saveManuscriptDetails on the Submission Domain Service should only update the data that related to the details before it returns the entire object?**
2. **Pulling together the entire `Submission` is the responsibility of the Submission Domain Service, (N-Service pattern) or is encapsulated in the `XpubSubmissionRootRepository`?**

**Comment by erezmus** [comment]
Decisions:
1. Move submission domain logic into Submission class.
2. XpubSubmissionRootRepository stores submission files, author, editors into respective tables. (e.g. author is stored in `team` table, manuscript file in `file` table)
3. Service layer above retrieves submission, orchestrates, updates and returns.

**Comment by diversemix** [comment]
Think we need to update: https://app.gitbook.com/@libero/s/libero-reviewer/bounded-contexts/design-principles

**Comment by erezmus** [comment]
So after trying out the decisions above on a branch, modifying the code to implement decisions above is going to take a while. I recommend we park this for now and focus on finishing functionality.

I discussed with noris steps we could take that would solve the problem i highlighted about ensuring we always return a full Submission to the client.

**Comment by diversemix** [comment]
would be good to make a record of those discussions.  We decided to pick up the question of repositories in the morning.

**Comment by giorgiosironi** [comment]
> would be good to make a record 

ADRs for the win?

**Comment by diversemix** [comment]
We will update the Design Priniciples - decision is to remove DTOs
