### ISSUE TITLE
Rational reasons for removing the Application Service layer

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#630]
This issue is record any rational reasons to remove the Application Service layer (dashboard, wizard, etc)

This layer exists to apply the application level permissions and to use the underlying services to fulfill the application requests incoming on the interface (resolvers). This layer decouples the application concerns from the Domain concerns - the 'S' in SOLID 

This issue exists to record any reasons why you think this layer should not exist. 

Especially for @norisalsaadie  :smile:

**Comment by hdrury1** [comment]
Closing this down, given that a lot of time went into the discussion and implementation of the different service layers. We should progress down this road until we have a seismic reason to pivot.
