### ISSUE TITLE
Investigate tagging of requests with an id

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#640]

**Comment by erkannt** [comment]
@diversemix Can you fill in/close this before leaving?

**Comment by diversemix** [comment]
@norisalsaadie ... I think this was your suggestion - do you want to expand on this?

**Comment by norisalsaadie** [comment]
The idea was to tag HTTP request with ID so that it can be traced through the logs, and this allows you to paint a picture about what went wrong when debugging. Inspired by Heroku (and other cloud providers) https://devcenter.heroku.com/articles/http-request-id

**Comment by erkannt** [comment]
Ok. I that case I'd consider this to definitely be techdebt. If this is a feature needed from infrastructure we ought to investigate general tooling like jaeger.

**Comment by erkannt** [comment]
Closing as there currently isn't a need for this.
