### ISSUE TITLE
Implement pubsub and connect to fileupload progress component

### ISSUE THREAD

**Issue by will-byrne** [libero/reviewer#653]
Connect to the endpoint on the server and pipe progress through to the file upload component to show progress of file upload.

**Comment by erezmus** [comment]
Trying with this:
```
        const uploadManuscriptFileProgress = useSubscription(manuscriptUploadProgressSubscription, {
            variables: { filename: files[0].name },
        });
```

But this would need to be called inside `onManuscriptUpload` in FileDetailsForm.tsx which brakes the holy tennets of hooks.

Solution is to have a generic subscription for all files with server filtering on user id:

```
fileUploadProgress: UploadProgress
```
