### ISSUE TITLE
Investigate OSX dependency issue with xml2json dependency

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer#658]
```gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/cory/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/Users/cory/.nvm/versions/node/v10.19.0/bin/node" "/Users/cory/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/cory/Dev/elife-xpub/node_modules/node-expat
```

replicate on osx 10.15.3 run yarn see output above. Seems to be a sub-dep of `xml2json`

**Comment by diversemix** [comment]
We need someone to try this fix .. https://github.com/buglabs/node-xml2json/issues/168#issuecomment-471363606

**Comment by diversemix** [comment]
Works for @will-byrne .... see https://elifesciences.slack.com/archives/C6LKMFK5Z/p1592315293338200

**Comment by norisalsaadie** [comment]
Unable to reproduce:

**Attempt 1**

macOS 10.15.5
yarn 1.22.4
node v12.18.0

commands:

    git clean -f
    rm -rf node_modules
    yarn

Output:

[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > io-ts@2.0.1" has unmet peer dependency "fp-ts@^2.0.0".
warning " > @libero/eslint-config@0.0.1" has unmet peer dependency "eslint@>= 3".
warning " > @libero/eslint-config@0.0.1" has unmet peer dependency "eslint-config-prettier@>=6".
warning " > @libero/eslint-config@0.0.1" has unmet peer dependency "eslint-plugin-prettier@>=3".
warning " > @typescript-eslint/eslint-plugin@2.8.0" has unmet peer dependency "eslint@^5.0.0 || ^6.0.0".
warning "@typescript-eslint/eslint-plugin > @typescript-eslint/experimental-utils@2.8.0" has unmet peer dependency "eslint@*".
warning " > @typescript-eslint/parser@2.8.0" has unmet peer dependency "eslint@^5.0.0 || ^6.0.0".
[5/5] 🔨  Building fresh packages...
✨  Done in 21.90s.

**Attempt 2**

macOS 10.15.5
yarn 1.22.4
commands:

    git clean -f
    rm -rf node_modules
    yarn cache clean
   node v12.18.0

Output:

yarn install v1.22.4
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > io-ts@2.0.1" has unmet peer dependency "fp-ts@^2.0.0".
warning " > @libero/eslint-config@0.0.1" has unmet peer dependency "eslint@>= 3".
warning " > @libero/eslint-config@0.0.1" has unmet peer dependency "eslint-config-prettier@>=6".
warning " > @libero/eslint-config@0.0.1" has unmet peer dependency "eslint-plugin-prettier@>=3".
warning " > @typescript-eslint/eslint-plugin@2.8.0" has unmet peer dependency "eslint@^5.0.0 || ^6.0.0".
warning "@typescript-eslint/eslint-plugin > @typescript-eslint/experimental-utils@2.8.0" has unmet peer dependency "eslint@*".
warning " > @typescript-eslint/parser@2.8.0" has unmet peer dependency "eslint@^5.0.0 || ^6.0.0".
[5/5] 🔨  Building fresh packages...
✨  Done in 42.99s.

**Comment by Cooryd** [comment]
I've tried following the CLT instructions described here https://github.com/nodejs/node-gyp/issues/1927 but running a 'node-gyp rebuild' is still failing so will need to re-look into this another time.

**Comment by Cooryd** [comment]
After using brew to uninstall `node` & `yarn` then manually removing my .node-gyp config file. I re-installed node, yarn and node-gyp and can now install and run all packages for submission. (for future reference I manually removed a lotof the config files listed here: https://stackabuse.com/how-to-uninstall-node-js-from-mac-osx/)
