### ISSUE TITLE
Add config server side for max file size

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#671]
Refer to xPub
* Max file size - https://github.com/elifesciences/elife-xpub/blob/732e8267bbb41fa6b2e68a021da60ab745c0d89e/config/default.js#L145
* Maximum number of files is stored on the client side in xPub (see packages/component-submission/client/utils/constants.js)  ... this should be in the same place as the above config

**Comment by norisalsaadie** [comment]
Server side config for max file finished and merged in.

**Comment by norisalsaadie** [comment]
Client side stuff moving to its own ticket. Closing as server side is done
