### ISSUE TITLE
Issues with websocket connections in staging

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#687]
Nothing connects to the websockets.

**Comment by diversemix** [comment]
I've found that running locally - everything is fine when using `yarn start:dev` however if I `make build && make start` then I get the same behaviour as in staging

**Comment by diversemix** [comment]
Now I am seeing errors like:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘http://localhost:3003/graphql’. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’).
```

**Comment by diversemix** [comment]
We need to decide on a way forward with this. One solution would be to use "add_header" commands in the nginx config. This would also mean it would be necessary for local development - this could be overcome by using a similar nginx container as the web server for local development - this needs thought and discussion.

**Comment by diversemix** [comment]
I'm currently looking at adding these headers into webpack-dev-server config

**Comment by diversemix** [comment]
Closing this off after a myriad of issues have been fixed:
- https://github.com/libero/reviewer-client/pull/178
- https://github.com/libero/reviewer-client/pull/177

**Comment by erkannt** [comment]
Required a change to the libero-reviewer-formula i.e. chart: https://github.com/elifesciences/libero-reviewer-formula/pull/18

**Comment by erkannt** [comment]
The switch of the backend protocol of the aws loadbalancer from http to tcp requires a new annotation to have the original request IP passed on.

See:
https://aws.amazon.com/premiumsupport/knowledge-center/elb-capture-client-ip-addresses/
https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html
https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#aws

Added with: https://github.com/elifesciences/libero-reviewer-formula/pull/19

**Comment by diversemix** [comment]
Check we are getting the client ip through - otherwise #694

**Comment by giorgiosironi** [comment]
A summary of [what we did for `elife-xpub`](https://github.com/elifesciences/builder/blob/master/projects/elife.yaml#L1813-L1815) if it's helpful.
The ELB there was forwarding all traffic from port 443 to port 443 on the EC2 servers. The EC2 servers were then responsible for HTTPS termination and needed the certificate to be deployed inside nginx.
A constraint of this chart instead (correct me if I am wrong) is that the ELB must terminate HTTPS and talk to the Service (and hence the Pods) with HTTP as they don't understand HTTPS.
Maybe the PROXY protocol solves this problem, but I have no experience with it.
