### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by norisalsaadie** [libero/reviewer#693]
Current config is Access-Control-Allow-Origin: '*'. Given that everything is going via a reverse proxy... there is probably no need for cors. Best to restrict

**Comment by diversemix** [comment]
We need to take a view on this... at the moment I'm assigning to TechDebt. Shout if you disagree...

/cc @norisalsaadie @hdrury1 @Cooryd @will-byrne

**Comment by norisalsaadie** [comment]
Can be found on Access-Control-Allow-Origin: *

**Comment by norisalsaadie** [comment]
Caused by apollo server defaults.

**Comment by norisalsaadie** [comment]
Less of a concern as Nginx is the proxy and the default CORS is better than apolloserver
