### ISSUE TITLE
Consider enabling Enable x-forwarded-for on Nginx 

### ISSUE THREAD

**Issue by norisalsaadie** [libero/reviewer#694]
We the host header is now being set at the nginx level, consider enabling the `X-Forwarded-For` setting

Ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For

**Comment by diversemix** [comment]
Putting into todo ... as its a simple task that could end up biting us if we don't have it in the future. /cc @hdrury1
