### ISSUE TITLE
minimist and acorn security alerts

### ISSUE THREAD

**Issue by erkannt** [libero/reviewer#705]
Definition of Done:

Address the two security alerts on `elife-xpub`

- [ ] https://github.com/elifesciences/elife-xpub/network/alert/tools/api-tests/yarn.lock/minimist/open
- [ ] https://github.com/elifesciences/elife-xpub/network/alert/tools/api-tests/yarn.lock/acorn/open

**Comment by diversemix** [comment]
This as been reopened as the previous change was reverted - due to the pipelines being faulty.

We should try again :)
