### ISSUE TITLE
Master failing unit test (upload supporting files)

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#710]
In reviewer-client caused by #686

**Comment by diversemix** [comment]
Example https://github.com/libero/reviewer-client/runs/567508816?check_suite_focus=true

**Comment by Cooryd** [comment]
https://github.com/libero/reviewer-client/runs/570987134 following the PR to fix bad console output we removed the supporting file test (to be rewritten later). We also fixed an I18n issue. Master CI looks to be passing correctly now https://github.com/libero/reviewer-client/runs/570987134
