### ISSUE TITLE
Potential issue with session affinity and pods

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#722]
There is possibly an issue ...
- When a client who is uploading a file to Pod-A
- Another pod could be handling the websockets
- This could result in undesirable behaviour

Answers on a thread  https://elifesciences.slack.com/archives/CNBPVEGNA/p1586264249018300

**Comment by diversemix** [comment]
The implementation in xPub is here: `pubsweet-server/src/graphql/pubsub`

```
    await client.connect()
    pubsub = new PostgresPubSub({ client })
    if (ignoreTerminatedError) {
      pubsub.subscribe('error', () => {})
    }
```

This uses the package `graphql-postgres-subscriptions` see - https://github.com/GraphQLCollege/graphql-postgres-subscriptions#readme

**Comment by norisalsaadie** [comment]
Let's verify the issue. It's possible sticky sessions will work

**Comment by erkannt** [comment]
Decided to go with sticky connections as part of #998
