### ISSUE TITLE
BUG - fails to upload a file 2MB in size

### ISSUE THREAD

**Issue by norisalsaadie** [libero/reviewer#730]
Error is as follows on a 2MB file:

HTTP/1.1 413 Request Entity Too Large
Server: nginx/1.17.9
Date: Thu, 09 Apr 2020 15:33:27 GMT
Content-Type: text/html
Content-Length: 183
Connection: close

**Comment by diversemix** [comment]
Fixed various issues throughout the day to get this working
- https://github.com/libero/reviewer-submission/pull/152
- https://github.com/libero/reviewer-client/pull/192
- https://github.com/libero/reviewer-client/pull/191
- https://github.com/libero/reviewer-client/pull/190
- https://github.com/libero/reviewer-client/pull/189

**Comment by diversemix** [comment]
Now we have an issue with S3 - as it expects the file to be streamed in 5Mb chunks ... 

FYI: in xPub we didn't do this - this is why we never had progress tracking this.

**Comment by diversemix** [comment]
However in the font end the files appear to be fine - think this is a bug!
/cc @will-byrne @Cooryd

**Comment by diversemix** [comment]
Closing in favour of #745
