### ISSUE TITLE
xPub - unable to click next after uploading supporting files

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#765]
Manuscript id `3d3acd0d-9bb3-4e47-a5c9-d57fe6c3dbd8`
Hotjar - https://insights.hotjar.com/r?site=443270&recording=3403898213

**Comment by diversemix** [comment]
Research done:
- logs are showing autosave happening very rapidly...  every < 100ms
- looking both in loggly and in the server logs does not show anything out of the ordinary

**Comment by diversemix** [comment]
I did notice from the recording that the user clicked next after uploading the manuscript and then returned to upload the supporting files.

I have tried repeating the same process - but it works for me so dunno what went on for the user.

**Comment by hdrury1** [comment]
If we're unable to replicate and the user subsequently completed the submission I think we should close this issue.
