### ISSUE TITLE
Add indeterminate spinner to file upload

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#766]
> Just fed back to @chugginselifesciences  - without seeing the hanging problem we’re happy to implement the indeterminate spinner with an “Uploading manuscript” label to inform the user that the application is working. 
@hdrury1 

This is to give the user feedback when uploading the file - we have found that there can be up to 1min delay before the upload progress is being fed back to the user.

**Comment by chugginselifesciences** [comment]
Thanks Peter. I've not had any luck getting to see the delay for myself in staging, but not a problem. I'm happy to wait if you don't mind giving me a heads up once you've got this working. 

I'm just wondering if 1 minute is an edge case? Or if you have an idea of what might be a more typical delay if that's based on extreme file size? Please don't do any work to find this out if you haven't already, it's not a problem if its unknown. But if you already have a rough idea it would be good to know. Thanks.
