### ISSUE TITLE
Update reviewer chart to match tidied up config

### ISSUE THREAD

**Issue by erezmus** [libero/reviewer#830]
Infrastructure work from #779 

Todo
- [ ] Client newrelic and hotjar config as configmap mounted file served through nginx
- [x] Continuum adaptor: move all config to environment variables
- [x] Submission: move all config to environment variables (client config is going into client)

**Comment by erezmus** [comment]
After chatting with @erkannt, we are considering two options for hotjar and newrelic config for the client:
1. Fetch the configuration on app load. Pro: Only one image is needed. Con: can be slower for user and if request fails, whole app doesn't load. also more complexity in client app code.

2. Settings are defined in global index.html file. As part of deployment, do a string replacement on the index.html file with environment variables with a script. Pros: still one image per build and we can have as many environments as we want. Con: Need to make sure that the script is run

**Comment by erkannt** [comment]
Closing in favour of #1107
