### ISSUE TITLE
How do we exercise browser tests in the pipeline

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#841]
Depending on #839 ... this will determine how the tests are run and which tools are used. 

From this decision we will need to create tickets for infrastructure and any scripts/actions to run the tests in the way chosen. This will affect the pipelines for the  umbrella repo and the staging pipeline.

**Comment by erkannt** [comment]
- succeeded in running nightwatch from within a container with chrome-webdriver
- testcafe already provides such an [image](https://github.com/DevExpress/testcafe/blob/master/docker/Dockerfile)

Ergo: we can probably package our tests into such a container and use it for testing in umbrella, staging and production.

- k8s has definitions for container based jobs
- helm has a hooks for test or parts to run after a release
- how to tie a browsertest-container into automated releases, monitoring, logging and alerting will require further discovery

**Comment by erkannt** [comment]
Created #865 and #867
