### ISSUE TITLE
Sciencebeam extraction not working in staging?

### ISSUE THREAD

**Issue by erkannt** [libero/reviewer#904]
```
{"level":30,"time":1589796836970,"pid":1,"hostname":"libero-reviewer--stg-submission-c9f755955-2sv7x","service":"reviewer-submission","realm":"infra","msg":"Sciencebeam extracting http://sciencebeam--stg:8075/api/convert","v":1}
{"level":50,"time":1589796856991,"pid":1,"hostname":"libero-reviewer--stg-submission-c9f755955-2sv7x","service":"reviewer-submission","realm":"infra","msg":"No response response recieved for
request","v":1}

```

Uploading the same file to https://sciencebeam--prod--test-cluster.elifesciences.org/api/convert produces valid xml...

**Comment by erkannt** [comment]
[dummy-manuscript.pdf](https://github.com/libero/reviewer/files/4643693/dummy-manuscript.pdf)
This file worked. But a real eLife paper doesn't.

**Comment by erkannt** [comment]
real eLife paper works once I bump the timout for sciencebeam from 20s to 60s. Processing this paper appears to take around 18s if I manually upload it to /api/convert

**Comment by erkannt** [comment]
I'm closing this as the timeout increase fixes the symptom. But I thinks its worth discussing.

@hdrury1 : from a UX perspective: What kind of timeout should we have? Note that we currently don't have a progress indicator for the sciencebeam stage. The progress just sits at 100% until sciencebeam is done or times out.

@de-code : What kind of processing times would you expect? Is this an area you are working on?

**Comment by hdrury1** [comment]
> @hdrury1 : from a UX perspective: What kind of timeout should we have? Note that we currently don't have a progress indicator for the sciencebeam stage. The progress just sits at 100% until sciencebeam is done or times out.

We should replicate the xPub timeout for now, pending evidence/feedback that this should change.

Why don't we have an indicator? Shouldn't there be an indeterminate spinner for Sciencebeam?

**Comment by erkannt** [comment]
re: Timout. xPub default is 20s. Reviewer deploys are now set to use this value as default.

re: indicator. Maybe now that we have a working staging again it is worth going over it? Or should we wait for decent browser test coverage being run against staging?
