### ISSUE TITLE
[Based on a short review balancing resilience as opposed to performance]

### ISSUE THREAD

**Issue by norisalsaadie** [libero/reviewer#907]
File upload and report of success are two separate requests/sockets. Ergo we need to ensure that both are handled by same submission instance or that the instances share information regarding this.

[Based on a short review balancing resilience as opposed to performance]

Instead of using postgres pub/sub as xPub did (as this would require engineering work). Consider using ingress cookie for /grapgql https://kubernetes.github.io/ingress-nginx/examples/affinity/cookie/ - speak to Daniel H

Consideration pod upgrades and traffic allocation between old vs new.

**Comment by erkannt** [comment]
Created #998
