### ISSUE TITLE
Investigate: How to run browser stack as part of github actions

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer#916]
Briefly look into whether browser stack is the best option for running browser tests again (quick look into Saucelabs).

Look into configuration needed to run the CI browser tests against browserstack. This sets us up to be able to test Edge, Safari ect.

**Comment by erkannt** [comment]
Integration into pipeline appears straightforward for both:

- https://github.com/DevExpress/testcafe-browser-provider-browserstack
- https://github.com/DevExpress/testcafe-browser-provider-saucelabs

Given that we already have an account with browserstack and any other differences appear to be negligible I'd say we go with Browserstack.

Looks like all we need to get going is a username and access key.
