### ISSUE TITLE
Decide on What and Where to test in the pipeline (browser tests)

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer#919]
Depends on #916 #918 

Introduce develop branch vs master in red state?
Document which browsers are tested against on PRS, merge and deployment.
What access / artefact output will be needed? (access to browserstack output / screenshots?)

**Comment by diversemix** [comment]
Decided that browser tests will be run on all PRs (as they don't take long - and they are run in parallel)

**Comment by erkannt** [comment]
Observations:

- running tests against saucelabs/browserstack is quicker than the containerized build and test step
- saucelabs/browserstack let us run five tests in parallel on the OSS license
- saucelabs/browserstack make screen recording, network and console logs available
- can either makes these publicly available or give devs accounts with the service


Decisions:

- run against all browsers on each PR, ergo no need for dev branch
- run against FF, Edge, Safari, Chrome(as sanity check)

Notes:

- if we start using these services a lot we need to make tests wait for sessions to become available #1002 
- saucelabs lets us make results public, can't find similar setting for browserstack
- saucelabs lets us specify `latest` and `latest-1` as the browser version, browserstack would need updating of target browsers
