### ISSUE TITLE
Manually test application at different view port sizes

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer#922]

**Comment by norisalsaadie** [comment]
Width with issues:

- 280px - grid is too wide requiring horizontal scroll 
- 768px - grid is too wide requiring horizontal scroll

**Comment by norisalsaadie** [comment]
Testing has taken place and tickets have been raised:

https://github.com/libero/reviewer/issues/1406

https://github.com/libero/reviewer/issues/1405

 https://github.com/libero/reviewer/issues/1404

https://github.com/libero/reviewer/issues/1403

https://github.com/libero/reviewer/issues/1402
