### ISSUE TITLE
Utilize return url functionality of continuum to simplify auth flow

### ISSUE THREAD

**Issue by erkannt** [libero/reviewer#983]
With the resolution of https://github.com/libero/reviewer/issues/837 we can simplify the authentication workflow and make it possible to have multiple deployment environments using the same continuum-login deployment.

ToDo after discussion with @erezmus.

 use ingress to:
- [x] append return url to to 301 redirect to continuum-login
- [x] append optional argument to get token as part of returned request
- [x] return directly to `/authenticate` instead of `/auth` (with optional argument, client no longer needed to process token)

Once successful: #888

**Comment by erezmus** [comment]
the " move redirect logic out of ingress into continuum-adaptor" is on ticket #888

**Comment by erkannt** [comment]
> the " move redirect logic out of ingress into continuum-adaptor" is on ticket #888

I've taken the liberty to add the client-code removal and doc update to that ticket and have removed them from this one.

**Comment by erkannt** [comment]
hypothesis 2:
After processing the login on sandbox.orcid.org there is a 302 chain: continuumtest--profiles/oauth2 > continuumtest--cdn-journal/log-in/check > continuumtest-cdn-jounarl/submit > reviewer/auth

The main difference I see between the working `/submit` and broken `/submit?return_url=...` is that in the working version `Referer:https://sandbox.orcid.org` but in the broken one has it set to `reviewer--staging...`.

**Comment by erkannt** [comment]
We have two issues:

- infinite 302 loop
- journal doesn't throw 400 even though redirect_url is not whitelisted

**Comment by erkannt** [comment]
Issues still persist after the merge of elifesciences/builder-configuration#144

created #1041 to track issue with whitelist being ignored

I am reverting staging to a working setup, but I have HAR network logs for whoever picks this up.

**Comment by erkannt** [comment]
My current suspicion (knowing zero PHP) is that once we return from orcid sandbox we for some reason enter[ this block](https://github.com/elifesciences/journal/blob/ba9270f9b5c93f25d2feb1784f183deb9c4d6574/src/Controller/SubmitController.php#L23) which ends up redirecting us back to orcid, thereby starting the redirect loop.

**Comment by erezmus** [comment]
set aside some time tomorrow with @nlisgo for join investigation

**Comment by erezmus** [comment]
looks like #1041 is fixed, when confirmed, we can update nginx ingress @erkannt

**Comment by erkannt** [comment]
Redirect is working. Currently only deployed to: https://reviewer--test-cluster.elifesciences.org so as to not break staging.

But I appears we aren't handling /authenticate with the token attached. I'm guessing that this needs to be fixed as part of #888? If so we can close this, but note that the current state leads to broken login. The changes are therefore currently in the `chart-dev` branch of `reviewer` and only applied to the 'prod' release on the cluster.

**Comment by erkannt** [comment]
The journal side of things is working and the `chart-dev` branch in `reviewer` is set up to utilize the new functionality. This branch is currently deployed to stg and prod on the test-cluster.

continuum-adaptor can't handle the token as a query, so I've created #1132 and am closing this.
