### ISSUE TITLE
Add client side validation and UI updates for people picker

### ISSUE THREAD

**Issue by hdrury1** [libero/reviewer#985]
The validation should match xPub and the following scenarios are allowed:

A user cannot exclude more than 2 Reviewing or Senior editors
A user cannot suggest more than 6 Reviewing or Senior editors (text displayed is 'Maximum 6 choices' once this is reached)
A user must suggest at least 2 Reviewing or Senior editors (text displayed is '2 more suggestions required' then '1 more suggestion required')

**Comment by Cooryd** [comment]
Include people picker ui change to display the error messages for validation

**Comment by Cooryd** [comment]
`opposedSeniorEditors` and `opposedReviewingEditors` already have validation rules for max selection. Just need to forward these through to the people picker. Do we need to (probably yes) disable further people picker selections if max has been reached?

**Comment by diversemix** [comment]
Please note the requirements do alter for "Feature Article" see https://docs.google.com/spreadsheets/d/1mm9e88WuUkZD9KYKfwuhpyL93JOfsICUSS7HpytOb5o/edit#gid=0

**Comment by Cooryd** [comment]
Looking through the requirements it might be bigger than a single issue of work. @norisalsaadie you might want to break this down into 

- people picker ui - validation message and disabling further selections if the max has been reached (see screenshot of xpub-staging for what the internal view of people picker looks like once you hit the limit)
<img width="1680" alt="Screenshot 2020-06-02 at 10 49 32" src="https://user-images.githubusercontent.com/22455561/83506232-c9868800-a4be-11ea-83e7-4b3a7967defb.png">
- Hooking up error messages to Editor Page and getting the validation configured for all People picker fields + variant for Feature Article (this will require injecting the initialValues articleType into a validationResolver as we did in details page)
