### ISSUE TITLE
Network disconnect js error in High Sierra browserstack

### ISSUE THREAD

**Issue by erkannt** [libero/reviewer#989]
Browserstack tests running in Safari on High Sierra sometimes fail with a js error `network disconnect`.

- appears only in high sierra
- not reproduceable when running browserstack against local machine instead of github vm

**Comment by erkannt** [comment]
Just had the error reproduce when running against my local machine.

**Comment by diversemix** [comment]
May be related to #1003

**Comment by diversemix** [comment]
Everything is working in SauceLabs
